import { createContext, useContext, type ReactNode } from "react";
import { ApiError, type Me } from "../api";

export const MeContext = createContext<Me | null>(null);
export function useMe(): Me {
  const me = useContext(MeContext);
  if (!me) throw new Error("useMe outside an authenticated layout");
  return me;
}
export function useCan(perm: string): boolean {
  return useMe().permissions.includes(perm);
}

const STATUS_TONE: Record<string, string> = {
  completed: "ok", supported: "ok", materialized: "ok", succeeded: "ok", ok: "ok", verdict: "ok", acquired: "ok", inspected: "ok",
  running: "info", queued: "neutral", created: "neutral", pending_retry: "warn", paused: "warn", unverified: "warn",
  invalid: "warn", unparseable: "warn", short_truncation: "warn", described_only: "warn", published_but_unavailable: "warn",
  missing: "danger", failed: "danger", blocked: "danger", cancelled: "neutral", unavailable: "danger", not_located: "danger",
  inaccessible: "danger", process_failed: "danger", timed_out: "danger", transport_failed: "danger", rate_limited: "danger",
  serving_incompatible: "danger", interrupted: "warn", downloaded: "ok", not_applicable: "neutral",
};

export function StatusBadge({ status, label }: { status: string; label?: string }) {
  const tone = STATUS_TONE[status] ?? "neutral";
  return (
    <span className={`badge ${tone === "neutral" ? "" : tone}`}>
      <span className="dot" aria-hidden="true" />
      {label ?? status.replace(/_/g, " ")}
    </span>
  );
}

export function Banner({ tone, title, children }: { tone: "warn" | "danger" | "info" | "ok"; title: string; children?: ReactNode }) {
  return (
    <div className={`banner ${tone}`} role={tone === "danger" ? "alert" : "status"}>
      <div>
        <strong>{title}</strong>
        {children ? <div className="muted">{children}</div> : null}
      </div>
    </div>
  );
}

export function SyntheticBanner({ show }: { show: boolean }) {
  if (!show) return null;
  return (
    <Banner tone="warn" title="Synthetic test fixture — not benchmark content">
      This dataset version was generated by the test fixture. Its instructions, screenshots, labels, and any scores are test
      data and must never be read as AgentHorizon results.
    </Banner>
  );
}

export function Loading({ label = "Loading" }: { label?: string }) {
  return (
    <div className="empty" aria-busy="true">
      <span className="spinner" aria-hidden="true" /> <span className="muted">{label}…</span>
    </div>
  );
}

export function Empty({ title, children }: { title: string; children?: ReactNode }) {
  return (
    <div className="empty">
      <h3>{title}</h3>
      {children ? <div className="muted">{children}</div> : null}
    </div>
  );
}

export function ErrorBox({ error }: { error: unknown }) {
  const e = error as ApiError;
  const title = e?.status === 401 ? "Not signed in" : e?.status === 403 ? "Not permitted" : e?.status === 404 ? "Not found" : "Request failed";
  return (
    <Banner tone="danger" title={title}>
      {e?.message ?? String(error)}
      {e?.requestId ? <span className="subtle"> · request {e.requestId}</span> : null}
    </Banner>
  );
}

export function Stat({ value, label, hint }: { value: ReactNode; label: string; hint?: string }) {
  return (
    <div className="stat" title={hint}>
      <span className="v">{value}</span>
      <span className="l">{label}</span>
    </div>
  );
}

export interface Segment { value: number; color: string; label: string }
export function Meter({ segments, total, ariaLabel }: { segments: Segment[]; total: number; ariaLabel: string }) {
  const t = total || 1;
  return (
    <div>
      <div className="meter" role="img" aria-label={`${ariaLabel}: ${segments.map((s) => `${s.label} ${s.value}`).join(", ")} of ${total}`}>
        {segments.filter((s) => s.value > 0).map((s) => (
          <span key={s.label} style={{ width: `${(100 * s.value) / t}%`, background: s.color }} />
        ))}
      </div>
      <div className="legend">
        {segments.map((s) => (
          <span key={s.label}>
            <i className="sw" style={{ background: s.color }} aria-hidden="true" /> {s.label} <strong>{s.value.toLocaleString()}</strong>
          </span>
        ))}
      </div>
    </div>
  );
}

export function Tabs<T extends string>({ tabs, value, onChange }: { tabs: { id: T; label: string }[]; value: T; onChange: (t: T) => void }) {
  return (
    <div className="tabs" role="tablist">
      {tabs.map((t) => (
        <button key={t.id} role="tab" aria-selected={value === t.id} onClick={() => onChange(t.id)}>
          {t.label}
        </button>
      ))}
    </div>
  );
}

export function KV({ rows }: { rows: [string, ReactNode][] }) {
  return (
    <dl className="kv">
      {rows.map(([k, v]) => (
        <div key={k} style={{ display: "contents" }}>
          <dt>{k}</dt>
          <dd>{v ?? "—"}</dd>
        </div>
      ))}
    </dl>
  );
}

export const C = {
  ok: "var(--ok)", warn: "var(--warn)", danger: "var(--danger)", info: "var(--info)", accent: "var(--accent)",
  neutral: "var(--border-strong)", muted: "var(--text-3)",
};

export function resultKindBadge(kind: string | undefined) {
  if (kind === "test_fixture") return <StatusBadge status="unverified" label="test fixture" />;
  if (kind === "new_paper_compatible") return <span className="badge ok">new paper-compatible run</span>;
  if (kind === "extension") return <span className="badge info">extension run</span>;
  return <span className="badge">{kind ?? "unknown"}</span>;
}
