"""Generate src/05_data.js: the example inputs plus facts about the Python reference build.

HX.data = {
  skill_md, skill_path, tool_catalog, policy, task, heldout_tasks,
  python_build: {initial_artifact_hash, refined_artifact_hash, catalog_digest, clause_count,
                 upstream_commit, generated_from}
}
"""

from __future__ import annotations

import json
import subprocess

from _common import BROWSER, ROOT, write

from hexis_service.demo import reference as R
from hexis_service.demo.env import compile_procurement, load_catalog, skill_source
from hexis_service.traces.update import propose_update

EX = ROOT / "examples" / "procurement_onboarding"

skill_md = (EX / "SKILL.md").read_text(encoding="utf-8")
catalog = json.loads((EX / "tool_catalog.json").read_text(encoding="utf-8"))
policy = json.loads((EX / "policy.json").read_text(encoding="utf-8"))
task = json.loads((EX / "task.json").read_text(encoding="utf-8"))
heldout = json.loads((ROOT / "evals" / "heldout_tasks.json").read_text(encoding="utf-8"))

comp = compile_procurement()
assert comp.status == "validated", comp.attempts
initial = comp.package
prop = propose_update(initial, R.missing_docs_trace(), [], [], load_catalog(), R.FixtureAligner(), skill_source().text)
assert prop.status == "CANDIDATE", prop.diagnostics
commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=ROOT).stdout.strip()

data = {
    "skill_md": skill_md,
    "skill_path": "examples/procurement_onboarding/SKILL.md",
    "tool_catalog": catalog,
    "policy": policy,
    "task": task,
    "heldout_tasks": heldout,
    "python_build": {
        "initial_artifact_hash": initial.artifact_hash,
        "refined_artifact_hash": prop.candidate.artifact_hash,
        "catalog_digest": load_catalog().digest(),
        "clause_count": len(initial.source_manifest.clauses),
        "upstream_commit": "96be2719ee79fc5071dc7eb2aeed816dc03aaa6c",
        "generated_from": commit,
    },
}
write("data", data)

js = ("/* GENERATED by golden/gen_data.py from the Python reference. Do not edit. */\n"
      "(function (HX) {\n  \"use strict\";\n  HX.data = " + json.dumps(data, sort_keys=True, indent=1, ensure_ascii=False) +
      ";\n})(globalThis.HX = globalThis.HX || {});\n")
(BROWSER / "src" / "05_data.js").write_text(js, encoding="utf-8")
print("05_data.js written:", data["python_build"])
