/* Parity of HX.guards with hexis_service/guards.py (golden/guards_*.json, generated by gen_guards.py). */
(function () {
  const G = HX.guards;
  const P = () => golden("guards_parse");
  const F = () => golden("guards_fuzz");
  const S = () => golden("guards_semantics");
  const D = () => golden("guards_disjoint");
  const U = () => golden("guards_unicode");

  const expr_of = (c) => (c.e16 ? String.fromCharCode(...c.e16) : c.e);
  const show = (s) => JSON.stringify(s).slice(0, 160);
  const SYN = "guard syntax error: ";
  /** JS AST -> the golden's JSON shape (float/complex values as Python repr strings, BigInt as {$int}). */
  function norm(node) {
    if (typeof node === "bigint") return { $int: node.toString() };
    if (Array.isArray(node)) return node.map(norm);
    if (node && typeof node === "object") {
      const out = {};
      for (const k of Object.keys(node)) out[k] = norm(node[k]);
      if (node.type === "Constant" && (node.py_type === "float" || node.py_type === "complex")) {
        const v = node.value;
        out.value = Number.isFinite(v) ? HX.canonical.py_float_repr(v) : Number.isNaN(v) ? "nan" : v > 0 ? "inf" : "-inf";
      }
      return out;
    }
    return node;
  }
  function attempt(fn) {
    try { return { ok: true, value: fn() }; } catch (e) { return { ok: false, err: e }; }
  }
  const dec_env = (env) => {
    const out = {};
    for (const k of Object.keys(env)) { /* own properties, also for "__proto__" */
      Object.defineProperty(out, k, { value: env[k] && env[k].$unknown === true ? G.UNKNOWN : env[k],
        enumerable: true, writable: true, configurable: true });
    }
    return out;
  };
  function collect(cases, check) {
    const bad = [];
    for (const c of cases) {
      const why = check(c);
      if (why) bad.push(why);
    }
    assert.deepEqual(bad.slice(0, 8), [], `${bad.length} mismatches`);
  }
  const DEV_RE = /outside the range supported by the JavaScript port|\\N\{\.\.\.\} escapes are not supported|surrogate code points are not supported/;

  /* ---------------------------------------------------------------------------------------- */
  /* parse                                                                                      */
  /* ---------------------------------------------------------------------------------------- */

  /** One golden parse record against G.parse (result and message) and G._parse_raw (tree, node count, depth). */
  function check_parse(c) {
    const e = expr_of(c);
    const r = attempt(() => G.parse(e));
    if (!r.ok && !(r.err instanceof G.GuardError)) return `${show(e)}: non-GuardError ${r.err}`;
    if (c.r === "ok" && !c.dev) {
      if (!r.ok) return `${show(e)}: JS rejects (${r.err.message}), Python accepts`;
      const vars = [...G.vars_of(e)];
      if (!HX.util.deep_equal(vars, c.vars)) return `${show(e)}: vars ${show(vars)} != ${show(c.vars)}`;
    } else if (c.r === "ok") {
      if (r.ok) return `${show(e)}: JS accepts a documented deviation`;
      if (!DEV_RE.test(r.err.message)) return `${show(e)}: deviation rejected with ${r.err.message}`;
    } else if (c.r === "err") {
      if (r.ok) return `${show(e)}: JS accepts, Python rejects: ${c.m}`;
      const m = r.err.message;
      /* Python's exact message, except syntax error texts (approximated) and texts with a \N escape, whose name
         validity the port cannot check */
      if (c.m.startsWith(SYN)) {
        if (!m.startsWith(SYN) && !c.nesc) return `${show(e)}: Python syntax error (${c.m}), JS: ${m}`;
      } else if (m !== c.m && !c.nesc) return `${show(e)}: message ${show(m)} != ${show(c.m)}`;
    } else if (r.ok) return `${show(e)}: JS accepts, Python raises ${c.x}`;
    /* the syntax level: the same parse success, tree, node count and depth as ast.parse */
    if (G._py_blank(e) || HX.util.codepoint_length(e) > G.MAX_LEN) return null; /* Python never parses these */
    const raw = attempt(() => G._parse_raw(e));
    if (!raw.ok && !(raw.err instanceof G.GuardError)) return `${show(e)}: _parse_raw non-GuardError ${raw.err}`;
    if (c.parsed) {
      if (!raw.ok) return `${show(e)}: _parse_raw fails (${raw.err.message}), Python parses`;
      const cnt = G._node_count(raw.value), dep = G._depth(raw.value);
      if (cnt !== c.nodes || dep !== c.depth) return `${show(e)}: nodes/depth ${cnt}/${dep} != ${c.nodes}/${c.depth}`;
      if (c.ast !== undefined && !HX.util.deep_equal(norm(raw.value), JSON.parse(c.ast))) {
        return `${show(e)}: tree ${show(norm(raw.value))}`;
      }
    } else if (raw.ok && !c.nesc) return `${show(e)}: JS parses text Python rejects (${c.m || c.x})`;
    return null;
  }

  test("guards.parse: results, messages, trees, node counts and depths equal Python on the hand-written corpus", () => {
    const cases = P().cases;
    assert.ok(cases.length >= 1250, "corpus too small");
    collect(cases, check_parse);
    const kinds = new Set(cases.map((c) => c.note));
    for (const k of ["f-string", "lambda", "comprehension", "subscript", "call", "display", "bytes and complex",
      "message order", "maximal depth", "repr probe", "deviation after Python's checks"]) assert.ok(kinds.has(k), k);
  });

  test("guards.parse: results, messages, trees, node counts and depths equal Python on 5000 random inputs", () => {
    const cases = F().cases;
    assert.ok(cases.length >= 5000);
    collect(cases, check_parse);
    const parsed = cases.filter((c) => c.parsed).length, accepted = cases.filter((c) => c.r === "ok").length;
    assert.ok(parsed > 1500 && accepted > 600, `coverage: ${parsed} parsed, ${accepted} accepted`);
  });

  test("guards: messages of rejected guards are Python's exact text (typecheck result, verifier's cases)", () => {
    /* typecheck returns [str(exc)] for a guard parse rejects */
    for (const c of P().cases.filter((c) => c.r === "err" && !c.m.startsWith(SYN) && !c.nesc)) {
      assert.deepEqual(G.typecheck(expr_of(c), {}), [c.m], expr_of(c));
    }
    const want = {
      "x == 1j": "constant not allowed: 1j", "x == b'a'": "constant not allowed: b'a'",
      "x in [*y]": "list literals may only contain constants", "empty(x for x in y)": "empty takes exactly one variable argument",
      "{1}": "syntax node not allowed: Set", "-{x}": "the only unary operator allowed is 'not'",
      "x == 1e400j": "constant not allowed: infj", "x == 1e16j": "constant not allowed: 1e+16j",
      "x == 1e15j": "constant not allowed: 1000000000000000j", "x == b'\\'\"'": "constant not allowed: b'\\'\"'",
      "x == b\"'\"": "constant not allowed: b\"'\"", "x in [f'a']": "list literals may only contain constants",
      "[9007199254740993, x]": "list literals may only contain constants",
    };
    for (const [e, m] of Object.entries(want)) assert.deepEqual(G.typecheck(e, { x: "number" }), [m], e);
    const big = ["x == 1"].concat(Array(11).fill("y == 2")).join(" and ") + " and x[0]";
    assert.deepEqual(G.typecheck(big, {}), ["guard has more than 64 syntax nodes"]);
    assert.equal(G.analyze_disjoint(["x == 1j", "x == 1"], { x: "number" }).detail, "unparseable guard: constant not allowed: 1j");
  });

  test("guards: corpus covers limit boundaries exactly (nodes 63/64/65, depth 12/13, list 32/33, str 256/257, len 512/513, 200/201 brackets)", () => {
    const by = new Map(P().cases.filter((c) => c.note).map((c) => [c.note, c]));
    const expect = {
      "63 nodes": "ok", "64 nodes": "ok", "65 nodes": "guard has more than 64 syntax nodes",
      "depth 12": "ok", "depth 13": "guard AST deeper than 12",
      "32 list items": "ok", "33 list items": "literal list longer than 32", "32 tuple items": "ok",
      "256-character string": "ok", "257-character string": "string literal too long",
      "256 astral characters": "ok", "257 astral characters": "string literal too long",
      "512 characters": "ok", "513 characters": "guard longer than 512 characters",
      "512 code points, astral": "ok", "513 code points, astral": "guard longer than 512 characters",
      "199 nested parentheses": "ok", "200 nested parentheses": "ok",
      "201 nested parentheses": "guard syntax error: too many nested parentheses",
      "lambda over 64 nodes": "guard has more than 64 syntax nodes", "f-string over 64 nodes": "guard has more than 64 syntax nodes",
      "nested f-strings, depth 12": "syntax node not allowed: JoinedStr",
      "nested f-strings deeper than 12": "guard AST deeper than 12", "33 complex items": "literal list longer than 32",
      "32 bytes items": "constant not allowed: b'a'",
    };
    for (const [note, want] of Object.entries(expect)) {
      const c = by.get(note);
      assert.ok(c, `corpus lacks ${note}`);
      assert.equal(c.r === "ok" ? "ok" : c.m, want, `Python result for ${note}`);
      const r = attempt(() => G.parse(expr_of(c)));
      assert.equal(r.ok ? "ok" : r.err.message, want, `JS result for ${note}`);
    }
    assert.equal(G._node_count(G.parse(by.get("64 nodes").e)), 64);
    assert.equal(G._depth(G.parse(by.get("depth 12").e)), 12);
  });

  test("guards: documented deviations are exactly big integer literals, \\N escapes, surrogate escapes and non-GuardError exceptions", () => {
    const all = P().cases.concat(F().cases);
    const dev = all.filter((c) => c.dev);
    assert.ok(dev.length >= 9);
    for (const c of dev) { /* Python accepts; the port rejects, after Python's own checks passed */
      const r = attempt(() => G.parse(expr_of(c)));
      assert.ok(!r.ok && r.err instanceof G.GuardError && DEV_RE.test(r.err.message), `${show(expr_of(c))}: ${r.ok || r.err.message}`);
    }
    assert.equal(P().cases.filter((c) => c.note === "JS deviation").length, 9);
    /* Python raises a non-GuardError from parse (and so from typecheck, evaluate, analyze_disjoint); the port
       raises GuardError: lone surrogates (UnicodeEncodeError), parser stack overflow in CPython's error pass on
       deeply nested invalid text (MemoryError), an f-string '=' field inside a format spec (ValueError), and an
       invalid escape in the text of an f-string format spec (UnicodeDecodeError) */
    const exc = all.filter((c) => c.r === "exc");
    const classes = new Set(exc.map((c) => c.x));
    assert.deepEqual([...classes].sort(), ["MemoryError", "UnicodeDecodeError", "UnicodeEncodeError", "ValueError"]);
    for (const c of exc) {
      const e = expr_of(c);
      const r = attempt(() => G.parse(e));
      assert.ok(!r.ok && r.err instanceof G.GuardError, `${show(e)} must be rejected with GuardError`);
      const m = r.err.message;
      if (c.x === "UnicodeEncodeError") assert.match(m, /lone surrogate/);
      if (c.x === "ValueError") assert.ok(/f-string '=' field inside a format specification/.test(m) || m.startsWith(SYN), m);
      if (c.x === "UnicodeDecodeError") assert.ok(m.startsWith(SYN) || c.nesc, m);
      if (c.x === "MemoryError") {
        assert.ok(m.startsWith(SYN), m); /* the text is invalid: the port reports the syntax error */
        let depth = 0, max = 0;
        for (const ch of e) { if ("([{".includes(ch)) max = Math.max(max, ++depth); else if (")]}".includes(ch)) depth--; }
        assert.ok(max >= 190, `MemoryError only at deep nesting, got ${max}`);
      }
      assert.deepEqual(G.typecheck(e, {}), [m]);
      assert.equal(G.analyze_disjoint([e, "x == 1"], { x: "integer" }).status, "UNKNOWN");
    }
    assert.ok(exc.some((c) => c.x === "MemoryError" && c.e.startsWith("[".repeat(193) + "x")), "verifier's MemoryError case");
    /* nothing CPython parses at maximal depth is rejected by the port */
    for (const c of P().cases.filter((c) => c.note === "maximal depth")) {
      assert.ok(c.parsed, `${show(c.e)} should parse in Python`);
      assert.ok(G._parse_raw(c.e), c.e.slice(0, 40));
    }
  });

  test("guards: deep nesting never escapes as RangeError; a small stack rejects with GuardError (child processes)", () => {
    const get = typeof process === "object" && process.getBuiltinModule;
    if (!get) return; /* Node < 22.3: no child process access from a classic script */
    const cp = process.getBuiltinModule("node:child_process");
    const script = `
      const fs = require("fs"), path = require("path"), vm = require("vm");
      const dir = path.join(process.env.HX_ROOT, "src");
      globalThis.HX = {};
      for (const f of fs.readdirSync(dir).filter((f) => /^\\d\\d_.*\\.js$/.test(f)).sort()) vm.runInThisContext(fs.readFileSync(path.join(dir, f), "utf8"));
      const G = HX.guards, out = {};
      const cases = { paren200: "(".repeat(200) + "x" + ")".repeat(200), list200: "[".repeat(200) + "x" + "]".repeat(200),
        inlist: "x in [" + "(".repeat(199) + "1" + ")".repeat(199) + "]", empty: "empty(" + "(".repeat(199) + "x" + ")".repeat(199) + ")",
        fstr: "f'{" + "(".repeat(199) + "x" + ")".repeat(199) + "}'", shallow: "x == 1 and not b" };
      for (const [k, e] of Object.entries(cases)) {
        try { G._parse_raw(e); out[k] = "ok"; } catch (x) { out[k] = x instanceof G.GuardError ? "GuardError" : x.name; }
        try { out[k + "_typecheck"] = G.typecheck(e, { x: "integer", b: "boolean" }).length; } catch (x) { out[k + "_typecheck"] = x.name; }
      }
      process.stdout.write(JSON.stringify(out));`;
    const run = (kb) => JSON.parse(cp.execFileSync(process.execPath, ["--stack-size=" + kb, "-e", script],
      { encoding: "utf8", env: Object.assign({}, process.env, { HX_ROOT: ROOT }) }));
    const normal = run(984);
    for (const k of ["paren200", "list200", "inlist", "empty", "fstr", "shallow"]) assert.equal(normal[k], "ok", `${k} at 984 KB`);
    const small = run(120); /* less than the ~250 KB the deepest guards need */
    for (const [k, v] of Object.entries(small)) {
      assert.ok(v === "ok" || v === "GuardError" || typeof v === "number", `${k}: ${v} at 120 KB`);
    }
    assert.equal(small.shallow, "ok");
    assert.equal(small.paren200, "GuardError");
    assert.equal(small.paren200_typecheck, 1);
    assert.ok(G._is_stack_overflow(new RangeError("Maximum call stack size exceeded")));
    assert.ok(!G._is_stack_overflow(new RangeError("Invalid array length")));
    assert.ok(!G._is_stack_overflow(new G.GuardError("x")));
  });

  /* ---------------------------------------------------------------------------------------- */
  /* typecheck / evaluate / evaluate3                                                           */
  /* ---------------------------------------------------------------------------------------- */

  test("guards.typecheck returns Python's exact error lists for 4 type environments", () => {
    const g = S();
    assert.ok(g.cases.length >= 900);
    collect(g.cases, (c) => {
      for (const [name, outcomes] of Object.entries(c.tc)) {
        const got = G.typecheck(c.e, g.type_envs[name]);
        if (!outcomes.some((o) => HX.util.deep_equal(o, got))) return `${show(c.e)} [${name}]: ${show(got)} not in ${show(outcomes)}`;
      }
      return null;
    });
  });

  test("guards.evaluate and evaluate3 match Python (values, Kleene UNKNOWN, error messages) on 8 environments", () => {
    const g = S();
    const envs = {};
    for (const [k, v] of Object.entries(g.value_envs)) envs[k] = dec_env(v);
    let errors = 0, unknowns = 0;
    collect(g.cases, (c) => {
      for (const name of Object.keys(envs)) {
        const r = attempt(() => G.evaluate(c.e, envs[name]));
        const got = r.ok ? r.value : r.err instanceof G.GuardError ? { error: r.err.message } : { crash: String(r.err) };
        if (!HX.util.deep_equal(got, c.ev[name])) return `evaluate ${show(c.e)} [${name}]: ${show(got)} != ${show(c.ev[name])}`;
        const r3 = attempt(() => G.evaluate3(c.e, envs[name]));
        const got3 = r3.ok ? r3.value : r3.err instanceof G.GuardError ? { error: r3.err.message } : { crash: String(r3.err) };
        if (!HX.util.deep_equal(got3, c.ev3[name])) return `evaluate3 ${show(c.e)} [${name}]: ${show(got3)} != ${show(c.ev3[name])}`;
        if (!r.ok) errors++;
        if (got3 === null) unknowns++;
      }
      return null;
    });
    assert.ok(errors > 500 && unknowns > 200, `coverage: ${errors} errors, ${unknowns} unknowns`);
  });

  /* ---------------------------------------------------------------------------------------- */
  /* analyze_disjoint                                                                           */
  /* ---------------------------------------------------------------------------------------- */

  const has_big = (v) => v && typeof v === "object" && (v.$int !== undefined || Object.values(v).some(has_big));

  test("guards.analyze_disjoint: status, edges, detail and counterexample match Python; counterexamples are real", () => {
    const cases = D().cases;
    assert.ok(cases.length >= 400);
    const stats = { same: 0, rep: 0, port_unknown: 0, literal_dev: 0, exc: 0, repr: 0 };
    collect(cases, (c) => {
      const an = G.analyze_disjoint(c.guards, c.types);
      if (Object.keys(an).sort().join() !== "counterexample,detail,edges,status") return `bad Analysis shape ${show(an)}`;
      if (c.x !== undefined) { /* Python raises a non-GuardError (deviations/guards.md); the port reports UNKNOWN */
        if (an.status !== "UNKNOWN" || !an.detail.startsWith("unparseable guard: ")) return `${show(c.guards)}: ${an.status} ${an.detail}`;
        stats.exc++;
        return null;
      }
      /* documented deviations: always UNKNOWN (conservative), never a different PROVEN/COUNTEREXAMPLE */
      if (an.status === "UNKNOWN" && /JavaScript port limitation/.test(an.detail)) {
        if (!c.big) return `${show(c.guards)}: port-limitation UNKNOWN without a big domain value`;
        stats.port_unknown++;
        return null;
      }
      if (an.status === "UNKNOWN" && /outside the range supported by the JavaScript port/.test(an.detail)) {
        stats.literal_dev++;
        return null;
      }
      if (an.status !== c.status) return `${show(c.guards)}: status ${an.status} (${an.detail}) != ${c.status} (${c.detail})`;
      if (!HX.util.deep_equal(an.edges, c.edges)) return `${show(c.guards)}: edges ${show(an.edges)} != ${show(c.edges)}`;
      const syn = "unparseable guard: " + SYN;
      if (c.detail.startsWith(syn) ? !an.detail.startsWith(syn) : an.detail !== c.detail) {
        return `${show(c.guards)}: detail ${show(an.detail)} != ${show(c.detail)}`;
      }
      if (/^repr:/.test(c.note || "")) stats.repr++;
      if (an.status === "COUNTEREXAMPLE") {
        for (const i of an.edges) {
          if (G.evaluate(c.guards[i], an.counterexample) !== true) return `${show(c.guards)}: counterexample does not satisfy guard ${i}`;
        }
        if (has_big(c.counterexample)) {
          stats.rep++;
          if (Object.keys(an.counterexample).join() !== Object.keys(c.counterexample).join()) return `${show(c.guards)}: counterexample keys`;
        } else if (!HX.util.deep_equal(an.counterexample, c.counterexample)) {
          return `${show(c.guards)}: counterexample ${show(an.counterexample)} != ${show(c.counterexample)}`;
        }
      } else if (Object.keys(an.counterexample).length || an.edges.length) return `${show(c.guards)}: non-empty counterexample`;
      stats.same++;
      return null;
    });
    assert.ok(stats.same > 380, JSON.stringify(stats));
    assert.ok(stats.literal_dev >= 5 && stats.port_unknown >= 1 && stats.exc >= 1, `deviations exercised: ${JSON.stringify(stats)}`);
    assert.ok(stats.repr >= 90, `repr probes: ${JSON.stringify(stats)}`);
  });

  test("guards.analyze_disjoint: review fixes (array membership UNKNOWN, exact probing near large constants)", () => {
    const types = { tags: "array" };
    for (const gs of [['"a" in tags', '"b" in tags'], ['"DOC-A" in tags', '"DOC-B" not in tags']]) {
      assert.ok(gs.every((g) => G.typecheck(g, types).length === 0));
      assert.notEqual(G.analyze_disjoint(gs, types).status, "PROVEN");
    }
    assert.equal(G.analyze_disjoint(["empty(tags)", "nonempty(tags)"], types).status, "PROVEN");
    for (const [gs, t] of [[["x > 1e20", "x > 5e19"], { x: "number" }], [["x > 1e300", "x > 1e299"], { x: "number" }],
      [["x > 0.1", "x < 0.10000000000000003"], { x: "number" }]]) {
      const an = G.analyze_disjoint(gs, t);
      assert.equal(an.status, "COUNTEREXAMPLE", gs.join(" / "));
      assert.ok(gs.every((g) => G.evaluate(g, an.counterexample)));
    }
    for (const [gs, t] of [[["x > 1e20", "x <= 1e20"], { x: "number" }], [["n > 2.5", "n < 3"], { n: "integer" }],
      [["x > 0.1", "x < 0.1"], { x: "number" }], [["0 <= x < 5", "5 <= x < 10"], { x: "number" }]]) {
      assert.equal(G.analyze_disjoint(gs, t).status, "PROVEN", gs.join(" / "));
    }
    assert.deepEqual(G.analyze_disjoint(["n > 2.5", "n < 3.5"], { n: "integer" }).counterexample, { n: 3 });
    for (const [gs, t] of [[["8.5 < x < 10", "x < 8.9"], { x: "number" }], [["1 < n < 10", "n == 2"], { n: "integer" }],
      [["0 <= x <= 5 < 100", "x > 4.5"], { x: "number" }]]) {
      assert.equal(G.analyze_disjoint(gs, t).status, "COUNTEREXAMPLE", gs.join(" / "));
    }
    /* property test of test_kernel.py over its whole hypothesis domain */
    const gs = ["validation_status == 'pass'", "validation_status == 'repairable' and repair_count < 2"];
    const vt = { validation_status: "string", repair_count: "integer" };
    assert.equal(G.analyze_disjoint(gs, vt).status, "PROVEN");
    for (const status of ["pass", "repairable", "fail", "other", ""]) {
      for (let n = -3; n <= 5; n++) {
        const env = { validation_status: status, repair_count: n };
        assert.ok(gs.filter((g) => G.evaluate(g, env)).length <= 1);
      }
    }
  });

  test("guards: deviation - an integer between adjacent doubles cannot be represented, analysis says UNKNOWN", () => {
    const an = G.analyze_disjoint(["n > 9007199254740992.0", "n < 9007199254740994.0"], { n: "integer" });
    assert.equal(an.status, "UNKNOWN"); /* Python: COUNTEREXAMPLE with n = 2**53 + 1 */
    assert.match(an.detail, /9007199254740993 .*JavaScript port limitation/);
    assert.equal(G.analyze_disjoint(["x > 1.7976931348623157e308", "x > 1e308"], { x: "number" }).status, "UNKNOWN");
    /* a big exact value with room in its region is replaced by a double from the same region */
    const big = G.analyze_disjoint(["x > 1e20", "x > 5e19"], { x: "number" });
    assert.equal(big.counterexample.x, G._next_up(1e20));
    assert.deepEqual(G._numeric_domain(false, [1e20, 5e19]),
      [0, 49999999999999999999n, 5e19, 50000000000000000001n, 1e20, 100000000000000000001n]);
  });

  /* ---------------------------------------------------------------------------------------- */
  /* Unicode facts, repr, API contract                                                         */
  /* ---------------------------------------------------------------------------------------- */

  test("guards: identifier tables, whitespace set and NFKC normalization equal CPython 3.12 (Unicode 15.0)", () => {
    const u = U();
    assert.equal(u.unidata_version, "15.0.0");
    const r = G._xid_ranges();
    assert.deepEqual(r.start, u.xid_start);
    assert.deepEqual(r.continue, u.xid_continue);
    assert.deepEqual(G._py_space().sort((a, b) => a - b), u.space);
    const parts = [];
    let changed = 0;
    for (let k = 0; k < u.xid_continue.length; k += 2) {
      for (let cp = Math.max(u.xid_continue[k], 0x80); cp <= u.xid_continue[k + 1]; cp++) {
        const c = String.fromCodePoint(cp);
        const s = G._is_xid_start(cp) ? c : "x" + c;
        const id = G._parse_raw(s).body.id;
        if (id !== s) changed++;
        parts.push(cp.toString(16) + "=" + id + "\n");
      }
    }
    assert.equal(changed, u.nfkc_changed);
    assert.equal(HX.canonical.sha256_hex(parts.join("")), u.nfkc_sha256);
  });

  test("guards: Python repr (str.isprintable table of Unicode 15.0, quotes, escapes) for message text", () => {
    const u = U();
    assert.deepEqual(G._nonprintable_ranges(), u.nonprintable);
    assert.ok(u.repr.length > 150);
    for (const s of u.repr) {
      const v = s.e16 ? String.fromCharCode(...s.e16) : s.e;
      assert.equal(G._py_repr_str(v), s.repr, JSON.stringify(v));
    }
    /* the verifier's case: U+3000 in a string literal of a guard quoted in an analysis detail */
    const an = G.analyze_disjoint(["x == y and s == '\u3000'", "x == 1"], { x: "integer", y: "integer", s: "string" });
    assert.equal(an.detail, "guard \"x == y and s == '\\u3000'\" compares two variables or tests membership in an array " +
      "variable; outside the enumerable fragment");
    assert.equal(G._py_repr_str("\ud800"), "'\\ud800'"); /* a lone surrogate is a Cs code point, as in Python */
    assert.equal(G._py_repr_bytes([0x27, 0x22, 0x5c, 0, 0x7f, 0x80, 0x41]), "b'\\'\"\\\\\\x00\\x7f\\x80A'");
    assert.deepEqual([1, 0, Infinity, 1e16, 1e15, 0.5, 1e-5].map(G._py_repr_imag),
      ["1j", "0j", "infj", "1e+16j", "1000000000000000j", "0.5j", "1e-05j"]);
  });

  test("guards: AST contract of PORTING.md (shapes, op names, py_type, frozen, cached)", () => {
    const t = G.parse("not (x == 1.0) and s in ['a', 2] or empty(arr)");
    assert.equal(t.type, "Expression");
    assert.equal(t.body.type, "BoolOp");
    assert.equal(t.body.op, "Or");
    const and = t.body.values[0];
    assert.deepEqual([and.type, and.op], ["BoolOp", "And"]);
    const not = and.values[0];
    assert.deepEqual([not.type, not.op], ["UnaryOp", "Not"]);
    assert.deepEqual(not.operand, { type: "Compare", left: { type: "Name", id: "x" }, ops: ["Eq"],
      comparators: [{ type: "Constant", value: 1, py_type: "float" }] });
    assert.deepEqual(and.values[1].comparators[0], { type: "List", elts: [
      { type: "Constant", value: "a", py_type: "str" }, { type: "Constant", value: 2, py_type: "int" }] });
    assert.deepEqual(t.body.values[1], { type: "Call", func: { type: "Name", id: "empty" }, args: [{ type: "Name", id: "arr" }], keywords: [] });
    assert.ok(Object.isFrozen(t) && Object.isFrozen(t.body.values[1].args));
    assert.equal(G.parse("not (x == 1.0) and s in ['a', 2] or empty(arr)"), t, "parse is cached");
    assert.deepEqual(G.parse("1 < n <= 4").body.ops, ["Lt", "LtE"]);
    assert.deepEqual(G.parse("x not in (1,)").body.ops, ["NotIn"]);
    assert.equal(G.parse("(1, 2)").body.type, "Tuple");
    assert.equal(G._CMP[G.parse("x != 1").body.ops[0]], "!=");
    assert.equal(G._const_type(G.parse("x == 2.0").body.comparators[0]), "number");
    assert.equal(G._const_type(G.parse("x == 2").body.comparators[0]), "integer");
    assert.deepEqual([G.MAX_LEN, G.MAX_DEPTH, G.MAX_NODES, G.MAX_LIST, G.MAX_STR, G.MAX_CONFIGS], [512, 12, 64, 32, 256, 20000]);
    assert.deepEqual([...G.PREDICATES], ["empty", "nonempty"]);
    assert.deepEqual([...G.NUMERIC], ["integer", "number"]);
    /* trees of rejected constructs (from _parse_raw): Python's node types, Store contexts explicit */
    const comp = G._parse_raw("[a for a, *b in c if d]").body;
    assert.equal(comp.type, "ListComp");
    assert.deepEqual(comp.generators[0].target, { type: "Tuple", ctx: "Store", elts: [{ type: "Name", id: "a", ctx: "Store" },
      { type: "Starred", ctx: "Store", value: { type: "Name", id: "b", ctx: "Store" } }] });
    assert.equal(G._parse_raw("f'{x!r:>{w}}'").body.values[0].conversion, 114);
  });

  test("guards: GuardError, UNKNOWN, vars_of, Map inputs and Python truthiness edge cases", () => {
    const r = attempt(() => G.parse("x +"));
    assert.ok(r.err instanceof G.GuardError && r.err instanceof HX.HXError);
    assert.equal(r.err.name, "GuardError");
    assert.equal(r.err.code, "GUARD");
    assert.match(r.err.message, /^guard syntax error: /);
    for (const bad of [null, undefined, 5, [], {}, "   ", "　 "]) {
      assert.throws(() => G.parse(bad), (e) => e instanceof G.GuardError && /empty guard/.test(e.message));
    }
    assert.equal(String(G.UNKNOWN), "UNKNOWN");
    assert.ok(!HX.util.is_plain_object(G.UNKNOWN));
    assert.throws(() => HX.canonical.canonical_text({ a: G.UNKNOWN }));
    assert.ok(G.vars_of("b and y == 1 and x in [1]") instanceof Set);
    assert.deepEqual([...G.vars_of("b and y == 1 and x in [1] and é and empty(arr) and empty(empty)")], ["arr", "b", "x", "y", "é"]);
    for (const falsy of ["", null, undefined, 0, false, []]) assert.equal(G.vars_of(falsy).size, 0);
    assert.throws(() => G.vars_of(" "), G.GuardError);
    assert.equal(G.evaluate("x == 1", new Map([["x", 1]])), true);
    assert.deepEqual(G.typecheck("x == 1", new Map([["x", "integer"]])), []);
    /* own properties only: prototype names are undefined variables, not inherited values */
    assert.throws(() => G.evaluate("constructor == 1", {}), /undefined variable 'constructor'/);
    assert.deepEqual(G.typecheck("toString", {}), ["undeclared variable 'toString'"]);
    assert.equal(G.evaluate("empty(__proto__)", JSON.parse('{"__proto__": []}')), true);
    /* evaluate3 uses Python truthiness for a non-boolean top-level result */
    assert.deepEqual(["1", "0", "''", "'a'", "[]", "[0]", "()", "0.0", "x"].map((e) => G.evaluate3(e, { x: G.UNKNOWN })),
      [true, false, false, true, false, true, false, false, null]);
    assert.throws(() => G.evaluate("1", {}), /did not evaluate to a boolean/);
    /* _is_bare_condition: names under and/or/not only */
    const bt = G.parse("b and not (c or x == y) and empty(z)");
    const names = G._walk(bt).filter((n) => n.type === "Name");
    assert.deepEqual(names.map((n) => [n.id, G._is_bare_condition(n, bt)]), /* ast.walk (BFS) order */
      [["b", true], ["empty", false], ["z", false], ["c", true], ["x", false], ["y", false]]);
    /* values outside JSON: conservative errors */
    assert.throws(() => G.evaluate("x == y", { x: undefined, y: undefined }), G.GuardError);
    assert.throws(() => G.evaluate("x == 1", { x: 1n }), G.GuardError);
  });

  test("guards: malicious guards (A03) and upstream-compatible subset", () => {
    for (const g of ["__import__('os').system('touch x') == 0", "draft.__class__ == 'x'", "open('m', 'w') == 1",
      "[x for x in validation_issues] == []", "lambda: 1", "not ".repeat(20) + "(validation_status == 'pass')"]) {
      assert.ok(G.typecheck(g, { validation_status: "string" }).length > 0, g);
    }
    const cases = [["x == 'a'", { x: "a" }, true], ["n < 3 and not ok", { n: 2, ok: false }, true],
      ["x in ['a', 'b']", { x: "c" }, false], ["empty(items) or n >= 5", { items: [], n: 1 }, true],
      ["nonempty(s)", { s: "z" }, true], ["1 < n < 4", { n: 3 }, true]];
    for (const [g, env, want] of cases) assert.equal(G.evaluate(g, env), want, g);
    assert.throws(() => G.evaluate("ghost == 1", {}), /undefined variable 'ghost'/);
    assert.throws(() => G.evaluate("flag == 1", { flag: true }), /equality between boolean and numeric/);
    /* Kleene: unknown and false is false; unknown or true is true; errors are never false */
    assert.equal(G.evaluate3("x == 1 and y", { x: G.UNKNOWN, y: false }), false);
    assert.equal(G.evaluate3("x == 1 or y", { x: G.UNKNOWN, y: true }), true);
    assert.equal(G.evaluate3("x == 1 or y", { x: G.UNKNOWN, y: false }), null);
    assert.throws(() => G.evaluate3("x == 1 and ghost", { x: G.UNKNOWN }), /undefined variable 'ghost'/);
    assert.throws(() => G.evaluate("x == 1", { x: G.UNKNOWN }), /has no observed value/);
  });
})();
