/* Parity of HX.guards with hexis_service/guards.py (golden/guards_*.json, generated by gen_guards.py). */
(function () {
  const G = HX.guards;
  const P = () => golden("guards_parse");
  const S = () => golden("guards_semantics");
  const D = () => golden("guards_disjoint");
  const U = () => golden("guards_unicode");

  const expr_of = (c) => (c.e16 ? String.fromCharCode(...c.e16) : c.e);
  const show = (s) => JSON.stringify(s).slice(0, 160);
  /** JS AST -> the golden's JSON shape (float constants as Python repr strings). */
  function norm(node) {
    if (Array.isArray(node)) return node.map(norm);
    if (node && typeof node === "object") {
      const out = {};
      for (const k of Object.keys(node)) out[k] = norm(node[k]);
      if (node.type === "Constant" && node.py_type === "float") {
        out.value = Number.isFinite(node.value) ? HX.canonical.py_float_repr(node.value) : node.value > 0 ? "inf" : "-inf";
      }
      return out;
    }
    return node;
  }
  function attempt(fn) {
    try { return { ok: true, value: fn() }; } catch (e) { return { ok: false, err: e }; }
  }
  const dec_env = (env) => {
    const out = {};
    for (const k of Object.keys(env)) { /* own properties, also for "__proto__" */
      Object.defineProperty(out, k, { value: env[k] && env[k].$unknown === true ? G.UNKNOWN : env[k],
        enumerable: true, writable: true, configurable: true });
    }
    return out;
  };
  function collect(cases, check) {
    const bad = [];
    for (const c of cases) {
      const why = check(c);
      if (why) bad.push(why);
    }
    assert.deepEqual(bad.slice(0, 8), [], `${bad.length} mismatches`);
  }

  /* ---------------------------------------------------------------------------------------- */
  /* parse                                                                                      */
  /* ---------------------------------------------------------------------------------------- */

  test("guards.parse accepts and rejects exactly like Python (hand-written corpus + random/mutated)", () => {
    assert.ok(P().cases.length >= 3250, "golden too small");
    collect(P().cases, (c) => {
      const e = expr_of(c);
      const r = attempt(() => G.parse(e));
      if (!r.ok && !(r.err instanceof G.GuardError)) return `${show(e)}: non-GuardError ${r.err}`;
      if (c.r === "ok" && !c.dev) {
        if (!r.ok) return `${show(e)}: JS rejects (${r.err.message}), Python accepts`;
        if (!HX.util.deep_equal(norm(r.value), c.ast)) return `${show(e)}: AST differs ${show(norm(r.value))}`;
        const vars = [...G.vars_of(e)];
        if (!HX.util.deep_equal(vars, c.vars)) return `${show(e)}: vars ${show(vars)} != ${show(c.vars)}`;
        return null;
      }
      if (r.ok) return `${show(e)}: JS accepts, Python ${c.r === "ok" ? "accepts but this is a documented deviation" : "rejects: " + (c.m || c.x)}`;
      if (c.r === "err" && c.bld && r.err.message !== c.m) return `${show(e)}: message ${show(r.err.message)} != ${show(c.m)}`;
      return null;
    });
  });

  test("guards: Python-shaped trees, node counts and depths match ast.walk/_depth for every buildable parse", () => {
    let n = 0;
    collect(P().cases.filter((c) => c.parsed && c.bld), (c) => {
      const e = expr_of(c);
      const r = attempt(() => G._parse_raw(e));
      if (!r.ok) return `${show(e)}: _parse_raw fails: ${r.err.message}`;
      n++;
      if (!HX.util.deep_equal(norm(r.value), c.ast)) return `${show(e)}: tree ${show(norm(r.value))}`;
      const cnt = G._node_count(r.value), dep = G._depth(r.value);
      if (cnt !== c.nodes || dep !== c.depth) return `${show(e)}: nodes/depth ${cnt}/${dep} != ${c.nodes}/${c.depth}`;
      return null;
    });
    assert.ok(n > 1500, `only ${n} buildable trees compared`);
  });

  test("guards: the port never builds a tree for text CPython's parser rejects", () => {
    collect(P().cases.filter((c) => !c.parsed), (c) => {
      const e = expr_of(c);
      if (G._py_blank(e) || HX.util.codepoint_length(e) > G.MAX_LEN) return null; /* Python never parsed it */
      const r = attempt(() => G._parse_raw(e));
      return r.ok ? `${show(e)}: JS parses text Python rejects as a syntax error` : null;
    });
  });

  test("guards: corpus covers limit boundaries exactly (nodes 63/64/65, depth 12/13, list 32/33, str 256/257, len 512/513, 200/201 brackets)", () => {
    const by = new Map(P().cases.filter((c) => c.note).map((c) => [c.note, c]));
    const expect = {
      "63 nodes": "ok", "64 nodes": "ok", "65 nodes": "guard has more than 64 syntax nodes",
      "depth 12": "ok", "depth 13": "guard AST deeper than 12",
      "32 list items": "ok", "33 list items": "literal list longer than 32", "32 tuple items": "ok",
      "256-character string": "ok", "257-character string": "string literal too long",
      "256 astral characters": "ok", "257 astral characters": "string literal too long",
      "512 characters": "ok", "513 characters": "guard longer than 512 characters",
      "512 code points, astral": "ok", "513 code points, astral": "guard longer than 512 characters",
      "199 nested parentheses": "ok", "200 nested parentheses": "ok",
      "201 nested parentheses": "guard syntax error: too many nested parentheses",
    };
    for (const [note, want] of Object.entries(expect)) {
      const c = by.get(note);
      assert.ok(c, `corpus lacks ${note}`);
      assert.equal(c.r === "ok" ? "ok" : c.m, want, `Python result for ${note}`);
      const r = attempt(() => G.parse(expr_of(c)));
      assert.equal(r.ok ? "ok" : r.err.message, want, `JS result for ${note}`);
    }
    assert.equal(G._node_count(G.parse(by.get("64 nodes").e)), 64);
    assert.equal(G._depth(G.parse(by.get("depth 12").e)), 12);
  });

  test("guards: documented deviations are exactly big integer literals, \\N escapes, surrogate escapes and lone surrogates", () => {
    const dev = P().cases.filter((c) => c.dev || c.r === "exc");
    assert.ok(dev.length >= 9);
    for (const c of dev) {
      const e = expr_of(c);
      const r = attempt(() => G.parse(e));
      assert.ok(!r.ok && r.err instanceof G.GuardError, `${show(e)} must be rejected with GuardError`);
      const m = r.err.message;
      const known = /outside the range supported by the JavaScript port|\\N\{\.\.\.\} escapes are not supported|surrogate code points are not supported|lone surrogate/.test(m);
      assert.ok(known, `${show(e)}: unexpected rejection reason ${m}`);
      if (c.r === "exc") assert.equal(c.x, "UnicodeEncodeError"); /* Python crashes instead of raising GuardError */
    }
    /* and nothing else deviates: every other JS-buildable Python acceptance is a JS acceptance (checked above) */
    const corpus_dev = P().cases.filter((c) => c.note === "JS deviation").map((c) => expr_of(c));
    assert.equal(corpus_dev.length, 9);
  });

  /* ---------------------------------------------------------------------------------------- */
  /* typecheck / evaluate / evaluate3                                                           */
  /* ---------------------------------------------------------------------------------------- */

  test("guards.typecheck returns Python's exact error lists for 4 type environments", () => {
    const g = S();
    assert.ok(g.cases.length >= 900);
    collect(g.cases, (c) => {
      for (const [name, outcomes] of Object.entries(c.tc)) {
        const got = G.typecheck(c.e, g.type_envs[name]);
        if (!outcomes.some((o) => HX.util.deep_equal(o, got))) return `${show(c.e)} [${name}]: ${show(got)} not in ${show(outcomes)}`;
      }
      return null;
    });
  });

  test("guards.evaluate and evaluate3 match Python (values, Kleene UNKNOWN, error messages) on 8 environments", () => {
    const g = S();
    const envs = {};
    for (const [k, v] of Object.entries(g.value_envs)) envs[k] = dec_env(v);
    let errors = 0, unknowns = 0;
    collect(g.cases, (c) => {
      for (const name of Object.keys(envs)) {
        const r = attempt(() => G.evaluate(c.e, envs[name]));
        const got = r.ok ? r.value : r.err instanceof G.GuardError ? { error: r.err.message } : { crash: String(r.err) };
        if (!HX.util.deep_equal(got, c.ev[name])) return `evaluate ${show(c.e)} [${name}]: ${show(got)} != ${show(c.ev[name])}`;
        const r3 = attempt(() => G.evaluate3(c.e, envs[name]));
        const got3 = r3.ok ? r3.value : r3.err instanceof G.GuardError ? { error: r3.err.message } : { crash: String(r3.err) };
        if (!HX.util.deep_equal(got3, c.ev3[name])) return `evaluate3 ${show(c.e)} [${name}]: ${show(got3)} != ${show(c.ev3[name])}`;
        if (!r.ok) errors++;
        if (got3 === null) unknowns++;
      }
      return null;
    });
    assert.ok(errors > 500 && unknowns > 200, `coverage: ${errors} errors, ${unknowns} unknowns`);
  });

  /* ---------------------------------------------------------------------------------------- */
  /* analyze_disjoint                                                                           */
  /* ---------------------------------------------------------------------------------------- */

  const has_big = (v) => v && typeof v === "object" && (v.$int !== undefined || Object.values(v).some(has_big));

  test("guards.analyze_disjoint: status, edges, detail and counterexample match Python; counterexamples are real", () => {
    const cases = D().cases;
    assert.ok(cases.length >= 400);
    const stats = { same: 0, rep: 0, port_unknown: 0, literal_dev: 0 };
    collect(cases, (c) => {
      const an = G.analyze_disjoint(c.guards, c.types);
      if (Object.keys(an).sort().join() !== "counterexample,detail,edges,status") return `bad Analysis shape ${show(an)}`;
      /* documented deviations: always UNKNOWN (conservative), never a different PROVEN/COUNTEREXAMPLE */
      if (an.status === "UNKNOWN" && /JavaScript port limitation/.test(an.detail)) {
        if (!c.big) return `${show(c.guards)}: port-limitation UNKNOWN without a big domain value`;
        stats.port_unknown++;
        return null;
      }
      if (an.status === "UNKNOWN" && /outside the range supported by the JavaScript port/.test(an.detail)) {
        stats.literal_dev++;
        return null;
      }
      if (an.status !== c.status) return `${show(c.guards)}: status ${an.status} (${an.detail}) != ${c.status} (${c.detail})`;
      if (!HX.util.deep_equal(an.edges, c.edges)) return `${show(c.guards)}: edges ${show(an.edges)} != ${show(c.edges)}`;
      if (an.detail !== c.detail) return `${show(c.guards)}: detail ${show(an.detail)} != ${show(c.detail)}`;
      if (an.status === "COUNTEREXAMPLE") {
        for (const i of an.edges) {
          if (G.evaluate(c.guards[i], an.counterexample) !== true) return `${show(c.guards)}: counterexample does not satisfy guard ${i}`;
        }
        if (has_big(c.counterexample)) {
          stats.rep++;
          if (Object.keys(an.counterexample).join() !== Object.keys(c.counterexample).join()) return `${show(c.guards)}: counterexample keys`;
        } else if (!HX.util.deep_equal(an.counterexample, c.counterexample)) {
          return `${show(c.guards)}: counterexample ${show(an.counterexample)} != ${show(c.counterexample)}`;
        }
      } else if (Object.keys(an.counterexample).length || an.edges.length) return `${show(c.guards)}: non-empty counterexample`;
      stats.same++;
      return null;
    });
    assert.ok(stats.same > 380, JSON.stringify(stats));
    assert.ok(stats.literal_dev >= 5 && stats.port_unknown >= 1, `deviations exercised: ${JSON.stringify(stats)}`);
  });

  test("guards.analyze_disjoint: review fixes (array membership UNKNOWN, exact probing near large constants)", () => {
    const types = { tags: "array" };
    for (const gs of [['"a" in tags', '"b" in tags'], ['"DOC-A" in tags', '"DOC-B" not in tags']]) {
      assert.ok(gs.every((g) => G.typecheck(g, types).length === 0));
      assert.notEqual(G.analyze_disjoint(gs, types).status, "PROVEN");
    }
    assert.equal(G.analyze_disjoint(["empty(tags)", "nonempty(tags)"], types).status, "PROVEN");
    for (const [gs, t] of [[["x > 1e20", "x > 5e19"], { x: "number" }], [["x > 1e300", "x > 1e299"], { x: "number" }],
      [["x > 0.1", "x < 0.10000000000000003"], { x: "number" }]]) {
      const an = G.analyze_disjoint(gs, t);
      assert.equal(an.status, "COUNTEREXAMPLE", gs.join(" / "));
      assert.ok(gs.every((g) => G.evaluate(g, an.counterexample)));
    }
    for (const [gs, t] of [[["x > 1e20", "x <= 1e20"], { x: "number" }], [["n > 2.5", "n < 3"], { n: "integer" }],
      [["x > 0.1", "x < 0.1"], { x: "number" }], [["0 <= x < 5", "5 <= x < 10"], { x: "number" }]]) {
      assert.equal(G.analyze_disjoint(gs, t).status, "PROVEN", gs.join(" / "));
    }
    assert.deepEqual(G.analyze_disjoint(["n > 2.5", "n < 3.5"], { n: "integer" }).counterexample, { n: 3 });
    for (const [gs, t] of [[["8.5 < x < 10", "x < 8.9"], { x: "number" }], [["1 < n < 10", "n == 2"], { n: "integer" }],
      [["0 <= x <= 5 < 100", "x > 4.5"], { x: "number" }]]) {
      assert.equal(G.analyze_disjoint(gs, t).status, "COUNTEREXAMPLE", gs.join(" / "));
    }
    /* property test of test_kernel.py over its whole hypothesis domain */
    const gs = ["validation_status == 'pass'", "validation_status == 'repairable' and repair_count < 2"];
    const vt = { validation_status: "string", repair_count: "integer" };
    assert.equal(G.analyze_disjoint(gs, vt).status, "PROVEN");
    for (const status of ["pass", "repairable", "fail", "other", ""]) {
      for (let n = -3; n <= 5; n++) {
        const env = { validation_status: status, repair_count: n };
        assert.ok(gs.filter((g) => G.evaluate(g, env)).length <= 1);
      }
    }
  });

  test("guards: deviation - an integer between adjacent doubles cannot be represented, analysis says UNKNOWN", () => {
    const an = G.analyze_disjoint(["n > 9007199254740992.0", "n < 9007199254740994.0"], { n: "integer" });
    assert.equal(an.status, "UNKNOWN"); /* Python: COUNTEREXAMPLE with n = 2**53 + 1 */
    assert.match(an.detail, /9007199254740993 .*JavaScript port limitation/);
    assert.equal(G.analyze_disjoint(["x > 1.7976931348623157e308", "x > 1e308"], { x: "number" }).status, "UNKNOWN");
    /* a big exact value with room in its region is replaced by a double from the same region */
    const big = G.analyze_disjoint(["x > 1e20", "x > 5e19"], { x: "number" });
    assert.equal(big.counterexample.x, G._next_up(1e20));
    assert.deepEqual(G._numeric_domain(false, [1e20, 5e19]),
      [0, 49999999999999999999n, 5e19, 50000000000000000001n, 1e20, 100000000000000000001n]);
  });

  /* ---------------------------------------------------------------------------------------- */
  /* Unicode facts, API contract                                                               */
  /* ---------------------------------------------------------------------------------------- */

  test("guards: identifier tables, whitespace set and NFKC normalization equal CPython 3.12 (Unicode 15.0)", () => {
    const u = U();
    assert.equal(u.unidata_version, "15.0.0");
    const r = G._xid_ranges();
    assert.deepEqual(r.start, u.xid_start);
    assert.deepEqual(r.continue, u.xid_continue);
    assert.deepEqual(G._py_space().sort((a, b) => a - b), u.space);
    const parts = [];
    let changed = 0;
    for (let k = 0; k < u.xid_continue.length; k += 2) {
      for (let cp = Math.max(u.xid_continue[k], 0x80); cp <= u.xid_continue[k + 1]; cp++) {
        const c = String.fromCodePoint(cp);
        const s = G._is_xid_start(cp) ? c : "x" + c;
        const id = G._parse_raw(s).body.id;
        if (id !== s) changed++;
        parts.push(cp.toString(16) + "=" + id + "\n");
      }
    }
    assert.equal(changed, u.nfkc_changed);
    assert.equal(HX.canonical.sha256_hex(parts.join("")), u.nfkc_sha256);
  });

  test("guards: AST contract of PORTING.md (shapes, op names, py_type, frozen, cached)", () => {
    const t = G.parse("not (x == 1.0) and s in ['a', 2] or empty(arr)");
    assert.equal(t.type, "Expression");
    assert.equal(t.body.type, "BoolOp");
    assert.equal(t.body.op, "Or");
    const and = t.body.values[0];
    assert.deepEqual([and.type, and.op], ["BoolOp", "And"]);
    const not = and.values[0];
    assert.deepEqual([not.type, not.op], ["UnaryOp", "Not"]);
    assert.deepEqual(not.operand, { type: "Compare", left: { type: "Name", id: "x" }, ops: ["Eq"],
      comparators: [{ type: "Constant", value: 1, py_type: "float" }] });
    assert.deepEqual(and.values[1].comparators[0], { type: "List", elts: [
      { type: "Constant", value: "a", py_type: "str" }, { type: "Constant", value: 2, py_type: "int" }] });
    assert.deepEqual(t.body.values[1], { type: "Call", func: { type: "Name", id: "empty" }, args: [{ type: "Name", id: "arr" }], keywords: [] });
    assert.ok(Object.isFrozen(t) && Object.isFrozen(t.body.values[1].args));
    assert.equal(G.parse("not (x == 1.0) and s in ['a', 2] or empty(arr)"), t, "parse is cached");
    assert.deepEqual(G.parse("1 < n <= 4").body.ops, ["Lt", "LtE"]);
    assert.deepEqual(G.parse("x not in (1,)").body.ops, ["NotIn"]);
    assert.equal(G.parse("(1, 2)").body.type, "Tuple");
    assert.equal(G._CMP[G.parse("x != 1").body.ops[0]], "!=");
    assert.equal(G._const_type(G.parse("x == 2.0").body.comparators[0]), "number");
    assert.equal(G._const_type(G.parse("x == 2").body.comparators[0]), "integer");
    assert.deepEqual([G.MAX_LEN, G.MAX_DEPTH, G.MAX_NODES, G.MAX_LIST, G.MAX_STR, G.MAX_CONFIGS], [512, 12, 64, 32, 256, 20000]);
    assert.deepEqual([...G.PREDICATES], ["empty", "nonempty"]);
    assert.deepEqual([...G.NUMERIC], ["integer", "number"]);
  });

  test("guards: GuardError, UNKNOWN, vars_of, Map inputs and Python truthiness edge cases", () => {
    const r = attempt(() => G.parse("x +"));
    assert.ok(r.err instanceof G.GuardError && r.err instanceof HX.HXError);
    assert.equal(r.err.name, "GuardError");
    assert.equal(r.err.code, "GUARD");
    assert.match(r.err.message, /^guard syntax error: /);
    for (const bad of [null, undefined, 5, [], {}, "   ", "　 "]) {
      assert.throws(() => G.parse(bad), (e) => e instanceof G.GuardError && /empty guard/.test(e.message));
    }
    assert.equal(String(G.UNKNOWN), "UNKNOWN");
    assert.ok(!HX.util.is_plain_object(G.UNKNOWN));
    assert.throws(() => HX.canonical.canonical_text({ a: G.UNKNOWN }));
    assert.ok(G.vars_of("b and y == 1 and x in [1]") instanceof Set);
    assert.deepEqual([...G.vars_of("b and y == 1 and x in [1] and é and empty(arr) and empty(empty)")], ["arr", "b", "x", "y", "é"]);
    for (const falsy of ["", null, undefined, 0, false, []]) assert.equal(G.vars_of(falsy).size, 0);
    assert.throws(() => G.vars_of(" "), G.GuardError);
    assert.equal(G.evaluate("x == 1", new Map([["x", 1]])), true);
    assert.deepEqual(G.typecheck("x == 1", new Map([["x", "integer"]])), []);
    /* own properties only: prototype names are undefined variables, not inherited values */
    assert.throws(() => G.evaluate("constructor == 1", {}), /undefined variable 'constructor'/);
    assert.deepEqual(G.typecheck("toString", {}), ["undeclared variable 'toString'"]);
    assert.equal(G.evaluate("empty(__proto__)", JSON.parse('{"__proto__": []}')), true);
    /* evaluate3 uses Python truthiness for a non-boolean top-level result */
    assert.deepEqual(["1", "0", "''", "'a'", "[]", "[0]", "()", "0.0", "x"].map((e) => G.evaluate3(e, { x: G.UNKNOWN })),
      [true, false, false, true, false, true, false, false, null]);
    assert.throws(() => G.evaluate("1", {}), /did not evaluate to a boolean/);
    /* _is_bare_condition: names under and/or/not only */
    const bt = G.parse("b and not (c or x == y) and empty(z)");
    const names = G._walk(bt).filter((n) => n.type === "Name");
    assert.deepEqual(names.map((n) => [n.id, G._is_bare_condition(n, bt)]), /* ast.walk (BFS) order */
      [["b", true], ["empty", false], ["z", false], ["c", true], ["x", false], ["y", false]]);
    /* values outside JSON: conservative errors */
    assert.throws(() => G.evaluate("x == y", { x: undefined, y: undefined }), G.GuardError);
    assert.throws(() => G.evaluate("x == 1", { x: 1n }), G.GuardError);
  });

  test("guards: malicious guards (A03) and upstream-compatible subset", () => {
    for (const g of ["__import__('os').system('touch x') == 0", "draft.__class__ == 'x'", "open('m', 'w') == 1",
      "[x for x in validation_issues] == []", "lambda: 1", "not ".repeat(20) + "(validation_status == 'pass')"]) {
      assert.ok(G.typecheck(g, { validation_status: "string" }).length > 0, g);
    }
    const cases = [["x == 'a'", { x: "a" }, true], ["n < 3 and not ok", { n: 2, ok: false }, true],
      ["x in ['a', 'b']", { x: "c" }, false], ["empty(items) or n >= 5", { items: [], n: 1 }, true],
      ["nonempty(s)", { s: "z" }, true], ["1 < n < 4", { n: 3 }, true]];
    for (const [g, env, want] of cases) assert.equal(G.evaluate(g, env), want, g);
    assert.throws(() => G.evaluate("ghost == 1", {}), /undefined variable 'ghost'/);
    assert.throws(() => G.evaluate("flag == 1", { flag: true }), /equality between boolean and numeric/);
    /* Kleene: unknown and false is false; unknown or true is true; errors are never false */
    assert.equal(G.evaluate3("x == 1 and y", { x: G.UNKNOWN, y: false }), false);
    assert.equal(G.evaluate3("x == 1 or y", { x: G.UNKNOWN, y: true }), true);
    assert.equal(G.evaluate3("x == 1 or y", { x: G.UNKNOWN, y: false }), null);
    assert.throws(() => G.evaluate3("x == 1 and ghost", { x: G.UNKNOWN }), /undefined variable 'ghost'/);
    assert.throws(() => G.evaluate("x == 1", { x: G.UNKNOWN }), /has no observed value/);
  });
})();
