import type { SourceRecord } from './types';

/**
 * Source records. Titles stay in their original language.
 *
 * status 'verified'  – URL, title and supporting text were confirmed through
 *                      search-index records during the build (direct page
 *                      fetching was blocked by the build sandbox).
 * status 'pending'   – a well-known citation recorded from the author's
 *                      knowledge; the build's search budget ran out before it
 *                      could be checked. Claims that rely only on pending
 *                      sources are flagged in the interface.
 *
 * See docs/VERIFICATION.md for the full audit trail.
 */

const MBOC = 'Alberts B, Johnson A, Lewis J, Raff M, Roberts K, Walter P';
const MBOC_BOOK = 'Molecular Biology of the Cell, 4th edition. New York: Garland Science';
const COOPER_BOOK = 'The Cell: A Molecular Approach, 2nd edition. Sunderland (MA): Sinauer Associates';
const PENDING_NOTE =
  'Not yet verified: well-known citation recorded from the author’s knowledge; the build environment’s search budget was exhausted before it could be checked. Run npm run check:links and confirm the claim.';

export const SOURCES: SourceRecord[] = [
  // ── Textbooks (NCBI Bookshelf) ─────────────────────────────────────────────
  {
    id: 'mboc4-book',
    type: 'book-section',
    title: 'Molecular Biology of the Cell, 4th edition',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: 'New York: Garland Science',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK21054/',
    status: 'verified',
    note: 'Search result returned the Bookshelf landing page “Molecular Biology of the Cell - NCBI Bookshelf” (NBK21054). Cited at book level for general textbook statements.',
  },
  {
    id: 'mboc4-internal-organization',
    type: 'book-section',
    title: 'Internal Organization of the Cell',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK21078/',
    status: 'verified',
    note: 'Search result returned “Internal Organization of the Cell - Molecular Biology of the Cell - NCBI Bookshelf” at this URL. Cited at part level.',
  },
  {
    id: 'mboc4-cytoskeleton',
    type: 'book-section',
    title: 'The Cytoskeleton',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK21051/',
    status: 'verified',
    note: 'Search result returned “The Cytoskeleton - Molecular Biology of the Cell - NCBI Bookshelf” at this URL. Chapter-level citation; the specific values cited from it are flagged as pending.',
  },
  {
    id: 'alberts-2002-lipid-bilayer',
    type: 'book-section',
    title: 'The Lipid Bilayer',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26871/',
    status: 'verified',
    note: 'Search for “The Lipid Bilayer” with the 5 × 10^6 lipids per µm² statement returned this URL.',
  },
  {
    id: 'alberts-2002-membrane-proteins',
    type: 'book-section',
    title: 'Membrane Proteins',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26878/',
    status: 'verified',
    note: 'Search for the sentence on protein making up about 50% of a typical plasma membrane’s mass returned this URL.',
  },
  {
    id: 'alberts-2002-table-12-1',
    type: 'table',
    title: 'Table 12-1, Relative Volumes Occupied by the Major Intracellular Compartments in a Liver Cell (Hepatocyte)',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: `${MBOC_BOOK} (Chapter 12)`,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26907/table/A2135/',
    status: 'verified',
    note: 'Confirmed independently by three searches (exact title and URL; cytosol 54%, mitochondria 22%, rough ER 9%, smooth ER + Golgi 6%, nucleus 6%, peroxisomes, lysosomes and endosomes 1% each).',
  },
  {
    id: 'alberts-2002-chromosomal-dna',
    type: 'book-section',
    title: 'Chromosomal DNA and Its Packaging in the Chromatin Fiber',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26834/',
    status: 'verified',
    note: 'Search for the exact section title returned this URL.',
  },
  {
    id: 'mboc4-from-rna-to-protein',
    type: 'book-section',
    title: 'From RNA to Protein',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26829/',
    status: 'verified',
    note: 'Search for the section title with ribosome/polyribosome terms returned this URL.',
  },
  {
    id: 'mboc4-endoplasmic-reticulum',
    type: 'book-section',
    title: 'The Endoplasmic Reticulum',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26841/',
    status: 'verified',
    note: 'Search for “The Endoplasmic Reticulum” with “more than half of the total membrane” returned this URL.',
  },
  {
    id: 'mboc4-golgi-transport',
    type: 'book-section',
    title: 'Transport from the ER through the Golgi Apparatus',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26941/',
    status: 'verified',
    note: 'Search for the exact section title returned this URL.',
  },
  {
    id: 'mboc4-membrane-transport',
    type: 'book-section',
    title: 'The Molecular Mechanisms of Membrane Transport and the Maintenance of Compartmental Diversity',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26859/',
    status: 'verified',
    note: 'Returned with this exact title at this URL in two searches about membrane transport.',
  },
  {
    id: 'mboc4-endocytosis',
    type: 'book-section',
    title: 'Transport into the Cell from the Plasma Membrane: Endocytosis',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26870/',
    status: 'verified',
    note: 'Search for endocytosis in Molecular Biology of the Cell returned this title and URL.',
  },
  {
    id: 'mboc4-peroxisomes',
    type: 'book-section',
    title: 'Peroxisomes',
    authors: MBOC,
    organization: 'NCBI Bookshelf',
    year: 2002,
    container: MBOC_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK26858/',
    status: 'verified',
    note: 'Search about peroxisomal plasmalogen synthesis returned this URL; the result was untitled and identified from its text as the MBoC peroxisome section.',
  },
  {
    id: 'cooper-2000-plasma-membrane',
    type: 'book-section',
    title: 'Structure of the Plasma Membrane',
    authors: 'Cooper GM',
    organization: 'NCBI Bookshelf',
    year: 2000,
    container: COOPER_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK9898/',
    status: 'verified',
    note: 'Search for the section title returned this URL; supports cholesterol present in about the same molar amount as phospholipids.',
  },
  {
    id: 'cooper-2000-endoplasmic-reticulum',
    type: 'book-section',
    title: 'The Endoplasmic Reticulum',
    authors: 'Cooper GM',
    organization: 'NCBI Bookshelf',
    year: 2000,
    container: COOPER_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK9889/',
    status: 'verified',
    note: 'Search for NBK9889 returned this section of Cooper’s The Cell (ER about half of membrane; lumen about 10% of cell volume).',
  },
  {
    id: 'cooper-2000-golgi-em',
    type: 'book-section',
    title: 'Figure 9.22, Electron micrograph of a Golgi apparatus',
    authors: 'Cooper GM',
    organization: 'NCBI Bookshelf',
    year: 2000,
    container: `${COOPER_BOOK} (section “The Golgi Apparatus”)`,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK9838/figure/A1500/?report=objectonly',
    status: 'verified',
    note: 'Search about cis and trans Golgi returned this figure page.',
  },
  {
    id: 'cooper-2000-golgi-regions',
    type: 'book-section',
    title: 'Figure 9.23, Regions of the Golgi apparatus',
    authors: 'Cooper GM',
    organization: 'NCBI Bookshelf',
    year: 2000,
    container: `${COOPER_BOOK} (section “The Golgi Apparatus”)`,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK9838/figure/A1501/?report=objectonly',
    status: 'verified',
    note: 'Same search returned this figure page; snippet described the ER–Golgi intermediate compartment and trans Golgi sorting.',
  },
  {
    id: 'cooper-2000-lysosomes',
    type: 'book-section',
    title: 'Lysosomes',
    authors: 'Cooper GM',
    organization: 'NCBI Bookshelf',
    year: 2000,
    container: COOPER_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK9953/',
    status: 'verified',
    note: 'Search about lysosomal hydrolytic enzymes returned this URL; identified from its text (acid hydrolases active near pH 5, cytosol about pH 7.2).',
  },
  {
    id: 'cooper-2000-peroxisomes',
    type: 'book-section',
    title: 'Peroxisomes',
    authors: 'Cooper GM',
    organization: 'NCBI Bookshelf',
    year: 2000,
    container: COOPER_BOOK,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK9930/',
    status: 'verified',
    note: 'Search about catalase, hydrogen peroxide, fatty-acid oxidation and plasmalogens returned this URL.',
  },
  // ── BioNumbers (Harvard Medical School) ───────────────────────────────────
  {
    id: 'bionumbers-101835',
    type: 'database',
    title: 'Rule of thumb for the thickness of lipid bilayer (BNID 101835)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Phillips R, Kondev J, Theriot J. Physical Biology of the Cell (2009), p. 26',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=101835',
    status: 'verified',
    note: 'Search returned this entry: 5 nm.',
  },
  {
    id: 'bionumbers-110373',
    type: 'database',
    title: 'Relative volumes occupied by the major compartments in a liver cell (hepatocyte) (BNID 110373)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Alberts et al., Molecular Biology of the Cell, 5th ed. (2008), Table 12-1',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=110373',
    status: 'verified',
    note: 'Searches returned this entry with the statement that membrane-enclosed compartments occupy nearly half the volume of a cell.',
  },
  {
    id: 'bionumbers-110374',
    type: 'database',
    title: 'Relative amounts of membrane types in two kinds of eucaryotic cells (BNID 110374)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Alberts et al., Molecular Biology of the Cell, 5th ed. (2008), Table 12-2',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=110374',
    status: 'verified',
    note: 'Two searches returned this entry: rough ER 35% (hepatocyte) / 60% (pancreatic exocrine cell) of membrane; inner mitochondrial membrane 32%; ER area 25× and 12× the plasma membrane.',
  },
  {
    id: 'bionumbers-104262',
    type: 'database',
    title: 'Nucleus fraction out of total cell volume in hepatocyte within liver parenchyma (BNID 104262)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=104262',
    status: 'verified',
    note: 'Search returned this entry: 5–10% of cell volume.',
  },
  {
    id: 'bionumbers-104208',
    type: 'database',
    title: 'Length of DNA in nucleus (BNID 104208)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=104208',
    status: 'verified',
    note: 'Search returned this entry: about 2 m for mammals (3 × 10^9 bp × 0.34 nm × 2).',
  },
  {
    id: 'bionumbers-113237',
    type: 'database',
    title: 'Mass of protein in hepatocyte (assuming edge length of 15 µm and protein concentration of 200 g/l) (BNID 113237)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=113237',
    status: 'verified',
    note: 'Returned with this exact title; only the title (stating the 200 g/L assumption) was seen.',
  },
  {
    id: 'bionumbers-113238',
    type: 'database',
    title: 'Volume of cell and mass of protein in thymocyte (assuming protein concentration of 200 g/l) (BNID 113238)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=113238',
    status: 'verified',
    note: 'Returned with this exact title; only the title (stating the 200 g/L assumption) was seen.',
  },
  {
    id: 'bionumbers-100483',
    type: 'database',
    title: 'Ribosome diameter (BNID 100483)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=100483',
    status: 'verified',
    note: 'Search returned this entry: about 30 nm generic, with a note of about 25 nm for mammalian ribosomes.',
  },
  {
    id: 'bionumbers-107347',
    type: 'database',
    title: 'Number of ribosomes in HeLa cells (BNID 107347)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Wolf SF, Schlessinger D. Biochemistry 1977;16(12):2783–2791',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=107347',
    status: 'verified',
    note: 'Search returned this entry: 9.5 × 10^6 ribosomes per HeLa cell.',
  },
  {
    id: 'bionumbers-107952',
    type: 'database',
    title: 'Rate at which ribosomes progress from 5′ ends of transcripts (BNID 107952)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Ingolia et al. 2011, Cell',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=107952',
    status: 'verified',
    note: 'Search returned this entry: 5.6 amino acids per second in mouse embryonic stem cells.',
  },
  {
    id: 'bionumbers-105782',
    type: 'database',
    title: 'Fraction of mitochondria out of total hepatocyte cell volume (BNID 105782)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=105782',
    status: 'verified',
    note: 'Search returned this entry consistent with 22%.',
  },
  {
    id: 'bionumbers-105783',
    type: 'database',
    title: 'Number of mitochondria in hepatocyte cell (BNID 105783)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Weibel ER et al. 1969, J Cell Biol',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=105783',
    status: 'verified',
    note: 'Search returned this entry: 1,665 per rat hepatocyte.',
  },
  {
    id: 'bionumbers-107490',
    type: 'database',
    title: 'Cytosolic free Ca2+ concentration of a resting cell (BNID 107490)',
    organization: 'BioNumbers, Harvard Medical School',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=107490',
    status: 'verified',
    note: 'Search returned this entry: about 100 nM.',
  },
  {
    id: 'bionumbers-112892',
    type: 'database',
    title: 'Ca2+ concentration in the ER lumen (BNID 112892)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Reference: Phillips MJ, Voeltz GK. Nat Rev Mol Cell Biol 2016;17(2):69–82',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=112892',
    status: 'verified',
    note: 'Search returned this URL (title field blank): ER lumen free Ca2+ about 60–500 µM.',
  },
  {
    id: 'bionumbers-112596',
    type: 'database',
    title: 'Kinetic characterization of vesicular stomatitis virus G [VSVG] trafficking in COS7 cells (BNID 112596)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Hirschberg et al. 1998, J Cell Biol',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=112596',
    status: 'verified',
    note: 'Search returned this entry: ER→Golgi 2.84 %/min, Golgi→plasma membrane 3.03 %/min.',
  },
  {
    id: 'bionumbers-112598',
    type: 'database',
    title: 'Average lifetime of a post Golgi carrier [PGC] before fusing with the plasma membrane in COS7 cells (BNID 112598)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Hirschberg et al. 1998, J Cell Biol',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=112598',
    status: 'verified',
    note: 'Search returned this entry: 3.8 minutes.',
  },
  {
    id: 'bionumbers-106072',
    type: 'database',
    title: 'Lysosome diameter (BNID 106072)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Kuehnel W. Color Atlas of Cytology, Histology and Microscopic Anatomy (2003)',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=106072',
    status: 'verified',
    note: 'Search returned this entry: typically 0.5 µm, range 0.1–1.2 µm.',
  },
  {
    id: 'bionumbers-107483',
    type: 'database',
    title: 'Number of lysosomes per cell (BNID 107483)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Dice JF, in Encyclopedia of Molecular Cell Biology and Molecular Medicine',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=107483',
    status: 'verified',
    note: 'Search returned this entry: 50 to 1,000 lysosomes per mammalian cell.',
  },
  {
    id: 'bionumbers-117094',
    type: 'database',
    title: 'Number of lysosomes in each mammalian cell (BNID 117094)',
    organization: 'BioNumbers, Harvard Medical School',
    container: 'Primary source: Yu L et al., Nature 2010',
    url: 'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=117094',
    status: 'verified',
    note: 'Search returned this entry: several hundred normally, fewer than 50 during nutrient starvation.',
  },
  // ── Research articles and reviews (verified) ───────────────────────────────
  {
    id: 'piovesan-2019',
    type: 'article',
    title: 'On the length, weight and GC content of the human genome',
    authors: 'Piovesan A, Pelleri MC, Antonaros F, Strippoli P, Caracausi M, Vitale L',
    year: 2019,
    container: 'BMC Research Notes 12:106',
    url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6391780/',
    doi: '10.1186/s13104-019-4137-z',
    status: 'verified',
    note: 'Search returned this PMC page: female diploid nucleus 6.37 Gbp, about 2.08 m, 6.51 pg; GC 40.9%.',
  },
  {
    id: 'nurk-2022',
    type: 'article',
    title: 'The complete sequence of a human genome',
    authors: 'Nurk S, Koren S, Rhie A, Rautiainen M, et al.',
    year: 2022,
    container: 'Science 376(6588):44–53',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9186530/',
    doi: '10.1126/science.abj6987',
    status: 'verified',
    note: 'Search returned this PMC page: 3.055 Gbp T2T-CHM13 assembly, nearly 200 Mbp of new sequence including the acrocentric short arms.',
  },
  {
    id: 'medlineplus-chromosomes',
    type: 'web',
    title: 'How many chromosomes do people have?',
    organization: 'MedlinePlus Genetics, U.S. National Library of Medicine',
    url: 'https://medlineplus.gov/genetics/understanding/basics/howmanychromosomes/',
    status: 'verified',
    note: 'Search returned this page: 46 chromosomes in 23 pairs; XX in females.',
  },
  {
    id: 'cremer-2010',
    type: 'review',
    title: 'Chromosome territories',
    authors: 'Cremer T, Cremer M',
    year: 2010,
    container: 'Cold Spring Harbor Perspectives in Biology 2(3):a003889',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2829961/',
    status: 'verified',
    note: 'Search for the title and article number returned this PMC page.',
  },
  {
    id: 'barr-bertram-1949',
    type: 'article',
    title:
      'A morphological distinction between neurones of the male and female, and the behaviour of the nucleolar satellite during accelerated nucleoprotein synthesis',
    authors: 'Barr ML, Bertram EG',
    year: 1949,
    container: 'Nature 163:676–677',
    url: 'https://doi.org/10.1038/163676a0',
    doi: '10.1038/163676a0',
    status: 'verified',
    note: 'Searches returned the nature.com PDF with title, authors and DOI.',
  },
  {
    id: 'embryo-project-lyon-1961',
    type: 'web',
    title: '“Gene Action in the X-chromosome of the Mouse (Mus musculus L.)” (1961), by Mary Lyon',
    organization: 'Embryo Project Encyclopedia, Arizona State University',
    url: 'https://embryo.asu.edu/pages/gene-action-x-chromosome-mouse-mus-musculus-l-1961-mary-lyon',
    status: 'verified',
    note: 'Search returned this page describing Lyon MF, Nature 190:372–373 (1961).',
  },
  {
    id: 'yang-2015-firre',
    type: 'article',
    title: 'The lncRNA Firre anchors the inactive X chromosome to the nucleolus by binding CTCF and maintains H3K27me3 methylation',
    authors: 'Yang F, Deng X, Ma W, et al.',
    year: 2015,
    container: 'Genome Biology 16:52',
    url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4391730/',
    doi: '10.1186/s13059-015-0618-0',
    status: 'verified',
    note: 'Search for the exact title returned this PMC page (mouse cells).',
  },
  {
    id: 'khatter-2015',
    type: 'article',
    title: 'Structure of the human 80S ribosome',
    authors: 'Khatter H, Myasnikov AG, Natchiar SK, Klaholz BP',
    year: 2015,
    container: 'Nature 520(7549):640–645',
    url: 'https://pubmed.ncbi.nlm.nih.gov/25901680/',
    doi: '10.1038/nature14427',
    status: 'verified',
    note: 'Search returned this PubMed record: 4.3 MDa; 60S = 28S, 5.8S, 5S rRNA + 47 proteins; 40S = 18S rRNA + 33 proteins.',
  },
  {
    id: 'anger-2013',
    type: 'article',
    title: 'Structures of the human and Drosophila 80S ribosome',
    authors: 'Anger AM, Armache JP, Berninghausen O, Habeck M, Subklewe M, Wilson DN, Beckmann R',
    year: 2013,
    container: 'Nature 497(7447):80–85',
    url: 'https://doi.org/10.1038/nature12104',
    doi: '10.1038/nature12104',
    status: 'verified',
    note: 'Searches returned the DOI record and PubMed entry with this title and authors.',
  },
  {
    id: 'natchiar-2017',
    type: 'article',
    title: 'Visualization of chemical modifications in the human 80S ribosome structure',
    authors: 'Natchiar SK, Myasnikov AG, Kratzat H, Hazemann I, Klaholz BP',
    year: 2017,
    container: 'Nature 551(7681):472–477',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29143818/',
    doi: '10.1038/nature24482',
    status: 'verified',
    note: 'Search returned this PubMed record: more than 130 modified rRNA nucleotides visible.',
  },
  {
    id: 'ingolia-2011',
    type: 'article',
    title: 'Ribosome profiling of mouse embryonic stem cells reveals the complexity and dynamics of mammalian proteomes',
    authors: 'Ingolia NT, Lareau LF, Weissman JS',
    year: 2011,
    container: 'Cell 147(4):789–802',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3225288/',
    status: 'verified',
    note: 'Search returned this PMC page: elongation about 5.6 codons per second in mouse embryonic stem cells.',
  },
  {
    id: 'nissen-2000',
    type: 'article',
    title: 'The structural basis of ribosome activity in peptide bond synthesis',
    authors: 'Nissen P, Hansen J, Ban N, Moore PB, Steitz TA',
    year: 2000,
    container: 'Science 289(5481):920–930',
    url: 'https://pubmed.ncbi.nlm.nih.gov/10937990/',
    status: 'verified',
    note: 'Two search summaries reported this title and PMID 10937990 (archaeal Haloarcula marismortui large subunit); the PubMed page itself did not appear as a result.',
  },
  {
    id: 'terasaki-2013',
    type: 'article',
    title: 'Stacked endoplasmic reticulum sheets are connected by helicoidal membrane motifs',
    authors: 'Terasaki M, Shemesh T, Kasthuri N, et al.',
    year: 2013,
    container: 'Cell 154(2):285–296',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3767119/',
    status: 'verified',
    note: 'Search for the exact title returned this PMC page (mouse salivary gland cells and neurons).',
  },
  {
    id: 'shibata-2010',
    type: 'article',
    title: 'Mechanisms determining the morphology of the peripheral ER',
    authors: 'Shibata Y, Shemesh T, Prinz WA, Palazzo AF, Kozlov MM, Rapoport TA',
    year: 2010,
    container: 'Cell 143(5):774–788',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3008339/',
    status: 'verified',
    note: 'Search returned this PMC page: mammalian ER sheets about 50 nm thick (about 30 nm in yeast); Climp63 spacer.',
  },
  {
    id: 'bolender-weibel-1973',
    type: 'article',
    title: 'A morphometric study of the removal of phenobarbital-induced membranes from hepatocytes after cessation of treatment',
    authors: 'Bolender RP, Weibel ER',
    year: 1973,
    container: 'Journal of Cell Biology 56(3):746',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2108940/',
    status: 'verified',
    note: 'Search returned this PMC page: rat hepatocyte smooth ER volume +100%, area +90% after 5 days; removed by autophagy within 5 days.',
  },
  {
    id: 'hirschberg-1998',
    type: 'article',
    title:
      'Kinetic analysis of secretory protein traffic and characterization of Golgi to plasma membrane transport intermediates in living cells',
    authors: 'Hirschberg K, Miller CM, Ellenberg J, Presley JF, Siggia ED, Phair RD, Lippincott-Schwartz J',
    year: 1998,
    container: 'Journal of Cell Biology 143(6):1485',
    url: 'https://rupress.org/jcb/article-abstract/143/6/1485/15976',
    status: 'verified',
    note: 'Search for the exact title returned this rupress.org URL and PMC2132993 (COS cells, VSVG-GFP).',
  },
  {
    id: 'tie-2025',
    type: 'article',
    title: 'Quantitative intra-Golgi transport and organization data suggest the stable compartment nature of the Golgi',
    authors: 'Tie HC, Wang H, Mahajan D, et al.',
    year: 2025,
    container: 'eLife (article 98582)',
    url: 'https://elifesciences.org/articles/98582',
    doi: '10.7554/eLife.98582',
    status: 'verified',
    note: 'Search returned this eLife page: Tac Golgi residence about 16 min in HeLa cells, about 3.4 h with a shortened luminal domain.',
  },
  {
    id: 'munro-2011',
    type: 'review',
    title: 'What is the Golgi apparatus, and why are we asking?',
    authors: 'Munro S',
    year: 2011,
    container: 'BMC Biology 9:63',
    url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3184113/',
    doi: '10.1186/1741-7007-9-63',
    status: 'verified',
    note: 'Search for the exact title returned this PMC page.',
  },
  {
    id: 'mazzarello-bentivoglio-1998',
    type: 'article',
    title: 'The centenarian Golgi apparatus',
    authors: 'Mazzarello P, Bentivoglio M',
    year: 1998,
    container: 'Nature 392(6676):543–544',
    url: 'https://doi.org/10.1038/33266',
    doi: '10.1038/33266',
    status: 'verified',
    note: 'Search returned a bibliographic record with this title, journal and DOI.',
  },
  {
    id: 'svoboda-1993',
    type: 'article',
    title: 'Direct observation of kinesin stepping by optical trapping interferometry',
    authors: 'Svoboda K, Schmidt CF, Schnapp BJ, Block SM',
    year: 1993,
    container: 'Nature 365(6448):721–727',
    url: 'https://www.nature.com/articles/365721a0',
    doi: '10.1038/365721a0',
    status: 'verified',
    note: 'Search returned nature.com/articles/365721a0 with a summary stating that kinesin moves with 8-nm steps.',
  },
  {
    id: 'traub-2011',
    type: 'article',
    title: 'Regarding the amazing choreography of clathrin coats',
    authors: 'Traub LM',
    year: 2011,
    container: 'PLoS Biology',
    url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3062531/',
    status: 'verified',
    note: 'Search returned this PMC page: clathrin-mediated endocytosis produces vesicles about 100 nm across.',
  },
  {
    id: 'xu-ren-2015',
    type: 'review',
    title: 'Lysosomal physiology',
    authors: 'Xu H, Ren D',
    year: 2015,
    container: 'Annual Review of Physiology 77:57–80',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4524569/',
    status: 'verified',
    note: 'Search returned this PMC page: more than 60 hydrolases and more than 50 membrane proteins.',
  },
  {
    id: 'mindell-2012',
    type: 'review',
    title: 'Lysosomal acidification mechanisms',
    authors: 'Mindell JA',
    year: 2012,
    container: 'Annual Review of Physiology 74:69–86',
    url: 'https://www.annualreviews.org/content/journals/10.1146/annurev-physiol-012110-142317',
    doi: '10.1146/annurev-physiol-012110-142317',
    status: 'verified',
    note: 'Search returned this page: lysosomal pH about 4.5–5.0, maintained by the V-ATPase.',
  },
  {
    id: 'platt-2018',
    type: 'review',
    title: 'Lysosomal storage diseases',
    authors: 'Platt FM, d’Azzo A, Davidson BL, Neufeld EF, Tifft CJ',
    year: 2018,
    container: 'Nature Reviews Disease Primers',
    url: 'https://link.springer.com/article/10.1038/s41572-018-0025-4',
    doi: '10.1038/s41572-018-0025-4',
    status: 'verified',
    note: 'Search returned this page: more than 70 disorders, together about 1 in 5,000 live births.',
  },
  {
    id: 'nobel-de-duve',
    type: 'web',
    title: 'Christian de Duve – Facts',
    organization: 'NobelPrize.org (Nobel Prize Outreach)',
    year: 1974,
    container: 'The Nobel Prize in Physiology or Medicine 1974',
    url: 'https://www.nobelprize.org/prizes/medicine/1974/duve/facts/',
    status: 'verified',
    note: 'Search returned this page; prize shared with Albert Claude and George E. Palade.',
  },
  {
    id: 'brown-goldstein-1985',
    type: 'web',
    title: 'A receptor-mediated pathway for cholesterol homeostasis (Nobel Lecture)',
    authors: 'Brown MS, Goldstein JL',
    organization: 'NobelPrize.org',
    year: 1985,
    url: 'https://www.nobelprize.org/uploads/2018/06/brown-goldstein-lecture-1.pdf',
    status: 'verified',
    note: 'Search returned this PDF: an LDL receptor makes a round trip about every 10 minutes during a roughly 20-hour life.',
  },
  {
    id: 'goldstein-brown-2009',
    type: 'review',
    title: 'The LDL receptor',
    authors: 'Goldstein JL, Brown MS',
    year: 2009,
    container: 'Arteriosclerosis, Thrombosis, and Vascular Biology',
    url: 'https://www.ahajournals.org/doi/10.1161/atvbaha.108.179564',
    doi: '10.1161/ATVBAHA.108.179564',
    status: 'verified',
    note: 'Search returned this page with the round-trip description.',
  },
  {
    id: 'steinman-1976',
    type: 'article',
    title: 'Membrane flow during pinocytosis. A stereologic analysis',
    authors: 'Steinman RM, Brodie SE, Cohn ZA',
    year: 1976,
    container: 'Journal of Cell Biology 68(3):665–687',
    url: 'https://rupress.org/jcb/article/68/3/665/18652/Membrane-flow-during-pinocytosis-A-stereologic',
    status: 'verified',
    note: 'Search returned this page: macrophages internalize 3.1% of their surface per minute (whole surface in about 33 min); L cells 0.8% per minute (about 125 min).',
  },
  {
    id: 'huotari-helenius-2011',
    type: 'review',
    title: 'Endosome maturation',
    authors: 'Huotari J, Helenius A',
    year: 2011,
    container: 'EMBO Journal 30:3481–3500',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3181477/',
    doi: '10.1038/emboj.2011.286',
    status: 'verified',
    note: 'Searches returned this PMC page: early endosomes pH 6.8–6.1, late endosomes 6.0–4.8, lysosomes about 4.5.',
  },
  {
    id: 'henne-2011',
    type: 'review',
    title: 'The ESCRT pathway',
    authors: 'Henne WM, Buchkovich NJ, Emr SD',
    year: 2011,
    container: 'Developmental Cell 21(1):77–91',
    url: 'https://doi.org/10.1016/j.devcel.2011.05.015',
    doi: '10.1016/j.devcel.2011.05.015',
    status: 'verified',
    note: 'Search confirmed the title, authors, volume, pages and DOI.',
  },
  {
    id: 'wanders-waterham-2006',
    type: 'review',
    title: 'Biochemistry of mammalian peroxisomes revisited',
    authors: 'Wanders RJA, Waterham HR',
    year: 2006,
    container: 'Annual Review of Biochemistry 75:295–332',
    url: 'https://pubmed.ncbi.nlm.nih.gov/16756494/',
    status: 'verified',
    note: 'Search returned this PubMed record (very-long-chain fatty acid oxidation; plasmalogen synthesis).',
  },
  {
    id: 'gould-1989',
    type: 'article',
    title: 'A conserved tripeptide sorts proteins to peroxisomes',
    authors: 'Gould SJ, Keller GA, Hosken N, Wilkinson J, Subramani S',
    year: 1989,
    container: 'Journal of Cell Biology 108(5):1657–1664',
    url: 'https://rupress.org/jcb/article/108/5/1657/11185/A-conserved-tripeptide-sorts-proteins-to',
    status: 'verified',
    note: 'Search for the exact title returned this rupress.org page.',
  },
  {
    id: 'pdb101-catalase',
    type: 'web',
    title: 'Molecule of the Month: Catalase',
    authors: 'Goodsell DS',
    organization: 'RCSB Protein Data Bank (PDB-101)',
    url: 'https://pdb101.rcsb.org/motm/57',
    status: 'verified',
    note: 'Search returned the identical page on PDB-101 mirror hosts (catalase breaks down millions of hydrogen peroxide molecules every second); the main-host URL is recorded.',
  },
  {
    id: 'wu-1992',
    type: 'article',
    title: 'Two independent mutational events in the loss of urate oxidase during hominoid evolution',
    authors: 'Wu X, Muzny DM, Lee CC, Caskey CT',
    year: 1992,
    container: 'Journal of Molecular Evolution 34(1):78–84',
    url: 'https://doi.org/10.1007/BF00163854',
    doi: '10.1007/BF00163854',
    status: 'verified',
    note: 'Search returned the title and DOI record.',
  },
  {
    id: 'usuda-1988',
    type: 'article',
    title: 'Tissue specificity and species differences in the distribution of urate oxidase in peroxisomes',
    authors: 'Usuda N, Reddy MK, Hashimoto T, Rao MS, Reddy JK',
    year: 1988,
    container: 'Laboratory Investigation 58(1):100–111',
    url: 'https://pubmed.ncbi.nlm.nih.gov/3336202/',
    status: 'verified',
    note: 'Search returned this PubMed record: urate oxidase in the crystalloid core of liver peroxisomes in rat, mouse, hamster, dog, cat and cow.',
  },
  // ── Pending verification (well-known citations; see docs/VERIFICATION.md) ──
  {
    id: 'beck-hurt-2017',
    type: 'review',
    title: 'The nuclear pore complex: understanding its function through structural insight',
    authors: 'Beck M, Hurt E',
    year: 2017,
    container: 'Nature Reviews Molecular Cell Biology 18(2):73–89',
    url: 'https://doi.org/10.1038/nrm.2016.147',
    doi: '10.1038/nrm.2016.147',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'ribbeck-gorlich-2001',
    type: 'article',
    title: 'Kinetic analysis of translocation through nuclear pore complexes',
    authors: 'Ribbeck K, Görlich D',
    year: 2001,
    container: 'EMBO Journal 20(6):1320–1330',
    url: 'https://doi.org/10.1093/emboj/20.6.1320',
    doi: '10.1093/emboj/20.6.1320',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'luger-1997',
    type: 'article',
    title: 'Crystal structure of the nucleosome core particle at 2.8 Å resolution',
    authors: 'Luger K, Mäder AW, Richmond RK, Sargent DF, Richmond TJ',
    year: 1997,
    container: 'Nature 389(6648):251–260',
    url: 'https://doi.org/10.1038/38444',
    doi: '10.1038/38444',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'moyzis-1988',
    type: 'article',
    title: 'A highly conserved repetitive DNA sequence, (TTAGGG)n, present at the telomeres of human chromosomes',
    authors: 'Moyzis RK, Buckingham JM, Cram LS, Dani M, Deaven LL, Jones MD, Meyne J, Ratliff RL, Wu JR',
    year: 1988,
    container: 'Proceedings of the National Academy of Sciences USA 85(18):6622–6626',
    url: 'https://doi.org/10.1073/pnas.85.18.6622',
    doi: '10.1073/pnas.85.18.6622',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'griffith-1999',
    type: 'article',
    title: 'Mammalian telomeres end in a large duplex loop',
    authors: 'Griffith JD, Comeau L, Rosenfield S, Stansel RM, Bianchi A, Moss H, de Lange T',
    year: 1999,
    container: 'Cell 97(4):503–514',
    url: 'https://doi.org/10.1016/S0092-8674(00)80760-6',
    doi: '10.1016/S0092-8674(00)80760-6',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'de-lange-2005',
    type: 'review',
    title: 'Shelterin: the protein complex that shapes and safeguards human telomeres',
    authors: 'de Lange T',
    year: 2005,
    container: 'Genes & Development 19(18):2100–2110',
    url: 'https://doi.org/10.1101/gad.1346005',
    doi: '10.1101/gad.1346005',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'harley-1990',
    type: 'article',
    title: 'Telomeres shorten during ageing of human fibroblasts',
    authors: 'Harley CB, Futcher AB, Greider CW',
    year: 1990,
    container: 'Nature 345(6274):458–460',
    url: 'https://doi.org/10.1038/345458a0',
    doi: '10.1038/345458a0',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'greider-blackburn-1985',
    type: 'article',
    title: 'Identification of a specific telomere terminal transferase activity in Tetrahymena extracts',
    authors: 'Greider CW, Blackburn EH',
    year: 1985,
    container: 'Cell 43(2 Pt 1):405–413',
    url: 'https://doi.org/10.1016/0092-8674(85)90170-9',
    doi: '10.1016/0092-8674(85)90170-9',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'aubert-lansdorp-2008',
    type: 'review',
    title: 'Telomeres and aging',
    authors: 'Aubert G, Lansdorp PM',
    year: 2008,
    container: 'Physiological Reviews 88(2):557–579',
    url: 'https://doi.org/10.1152/physrev.00026.2007',
    doi: '10.1152/physrev.00026.2007',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'lewis-tollervey-2000',
    type: 'review',
    title: 'Like attracts like: getting RNA processing together in the nucleus',
    authors: 'Lewis JD, Tollervey D',
    year: 2000,
    container: 'Science 288(5470):1385–1389',
    url: 'https://doi.org/10.1126/science.288.5470.1385',
    doi: '10.1126/science.288.5470.1385',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'boisvert-2007',
    type: 'review',
    title: 'The multifunctional nucleolus',
    authors: 'Boisvert FM, van Koningsbruggen S, Navascués J, Lamond AI',
    year: 2007,
    container: 'Nature Reviews Molecular Cell Biology 8(7):574–585',
    url: 'https://doi.org/10.1038/nrm2184',
    doi: '10.1038/nrm2184',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'feric-2016',
    type: 'article',
    title: 'Coexisting liquid phases underlie nucleolar subcompartments',
    authors: 'Feric M, Vaidya N, Harmon TS, Mitrea DM, Zhu L, Richardson TM, Kriwacki RW, Pappu RV, Brangwynne CP',
    year: 2016,
    container: 'Cell 165(7):1686–1697',
    url: 'https://doi.org/10.1016/j.cell.2016.04.047',
    doi: '10.1016/j.cell.2016.04.047',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'hu-2011',
    type: 'review',
    title: 'Weaving the web of ER tubules',
    authors: 'Hu J, Prinz WA, Rapoport TA',
    year: 2011,
    container: 'Cell 147(6):1226–1231',
    url: 'https://doi.org/10.1016/j.cell.2011.11.022',
    doi: '10.1016/j.cell.2011.11.022',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'yildiz-2004',
    type: 'article',
    title: 'Kinesin walks hand-over-hand',
    authors: 'Yildiz A, Tomishige M, Vale RD, Selvin PR',
    year: 2004,
    container: 'Science 303(5658):676–678',
    url: 'https://doi.org/10.1126/science.1093753',
    doi: '10.1126/science.1093753',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'schnitzer-block-1997',
    type: 'article',
    title: 'Kinesin hydrolyses one ATP per 8-nm step',
    authors: 'Schnitzer MJ, Block SM',
    year: 1997,
    container: 'Nature 388(6640):386–390',
    url: 'https://doi.org/10.1038/41111',
    doi: '10.1038/41111',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'anderson-1981',
    type: 'article',
    title: 'Sequence and organization of the human mitochondrial genome',
    authors: 'Anderson S, Bankier AT, Barrell BG, et al.',
    year: 1981,
    container: 'Nature 290(5806):457–465',
    url: 'https://doi.org/10.1038/290457a0',
    doi: '10.1038/290457a0',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'noji-1997',
    type: 'article',
    title: 'Direct observation of the rotation of F1-ATPase',
    authors: 'Noji H, Yasuda R, Yoshida M, Kinosita K Jr',
    year: 1997,
    container: 'Nature 386(6622):299–302',
    url: 'https://doi.org/10.1038/386299a0',
    doi: '10.1038/386299a0',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'watt-2010',
    type: 'article',
    title: 'Bioenergetic cost of making an adenosine triphosphate molecule in animal mitochondria',
    authors: 'Watt IN, Montgomery MG, Runswick MJ, Leslie AGW, Walker JE',
    year: 2010,
    container: 'Proceedings of the National Academy of Sciences USA 107(39):16823–16827',
    url: 'https://doi.org/10.1073/pnas.1011099107',
    doi: '10.1073/pnas.1011099107',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'mitchison-kirschner-1984',
    type: 'article',
    title: 'Dynamic instability of microtubule growth',
    authors: 'Mitchison T, Kirschner M',
    year: 1984,
    container: 'Nature 312(5991):237–242',
    url: 'https://doi.org/10.1038/312237a0',
    doi: '10.1038/312237a0',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'mullins-1998',
    type: 'article',
    title:
      'The interaction of Arp2/3 complex with actin: nucleation, high affinity pointed end capping, and formation of branching networks of filaments',
    authors: 'Mullins RD, Heuser JA, Pollard TD',
    year: 1998,
    container: 'Proceedings of the National Academy of Sciences USA 95(11):6181–6186',
    url: 'https://doi.org/10.1073/pnas.95.11.6181',
    doi: '10.1073/pnas.95.11.6181',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'pollard-1986',
    type: 'article',
    title: 'Rate constants for the reactions of ATP- and ADP-actin with the ends of actin filaments',
    authors: 'Pollard TD',
    year: 1986,
    container: 'Journal of Cell Biology 103(6):2747–2754',
    url: 'https://doi.org/10.1083/jcb.103.6.2747',
    doi: '10.1083/jcb.103.6.2747',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'pollard-cooper-2009',
    type: 'review',
    title: 'Actin, a central player in cell shape and movement',
    authors: 'Pollard TD, Cooper JA',
    year: 2009,
    container: 'Science 326(5957):1208–1212',
    url: 'https://doi.org/10.1126/science.1175862',
    doi: '10.1126/science.1175862',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'herrmann-aebi-2016',
    type: 'review',
    title: 'Intermediate filaments: structure and assembly',
    authors: 'Herrmann H, Aebi U',
    year: 2016,
    container: 'Cold Spring Harbor Perspectives in Biology 8(11):a018242',
    url: 'https://doi.org/10.1101/cshperspect.a018242',
    doi: '10.1101/cshperspect.a018242',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'szeverenyi-2008',
    type: 'article',
    title: 'The Human Intermediate Filament Database: comprehensive information on a gene family involved in many human diseases',
    authors: 'Szeverenyi I, Cassidy AJ, Chung CW, et al.',
    year: 2008,
    container: 'Human Mutation 29(3):351–360',
    url: 'https://doi.org/10.1002/humu.20652',
    doi: '10.1002/humu.20652',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'kreplak-2005',
    type: 'article',
    title: 'Exploring the mechanical behavior of single intermediate filaments',
    authors: 'Kreplak L, Bär H, Leterrier JF, Herrmann H, Aebi U',
    year: 2005,
    container: 'Journal of Molecular Biology 354(3):569–577',
    url: 'https://doi.org/10.1016/j.jmb.2005.09.092',
    doi: '10.1016/j.jmb.2005.09.092',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'nigg-raff-2009',
    type: 'review',
    title: 'Centrioles, centrosomes, and cilia in health and disease',
    authors: 'Nigg EA, Raff JW',
    year: 2009,
    container: 'Cell 139(4):663–678',
    url: 'https://doi.org/10.1016/j.cell.2009.10.036',
    doi: '10.1016/j.cell.2009.10.036',
    status: 'pending',
    note: PENDING_NOTE,
  },
  {
    id: 'bornens-2012',
    type: 'review',
    title: 'The centrosome in cells and organisms',
    authors: 'Bornens M',
    year: 2012,
    container: 'Science 335(6067):422–426',
    url: 'https://doi.org/10.1126/science.1209037',
    doi: '10.1126/science.1209037',
    status: 'pending',
    note: PENDING_NOTE,
  },
];
