// Generates src/styles/fonts.generated.css from the @fontsource packages.
//
// Why: the stock @fontsource stylesheets list both WOFF2 and WOFF sources,
// which makes the build copy every legacy WOFF file as well. All supported
// browsers read WOFF2, so this script keeps only WOFF2 sources and only the
// subsets the seven interface languages need (Latin, Latin Extended for
// Serbian Latin, Cyrillic for Russian; Noto Sans SC for Simplified Chinese).
// Browsers download a slice only when the page uses a character in its
// unicode-range, so the CJK rules cost nothing on non-Chinese pages.
//
// Run: node scripts/gen-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputs = {
  main: resolve(root, 'src/styles/fonts.generated.css'),
  zh: resolve(root, 'src/styles/fonts-zh.generated.css'),
};

const wanted = [
  { pkg: 'alegreya', files: ['500.css', '700.css', '500-italic.css'], out: 'main' },
  { pkg: 'alegreya-sans', files: ['400.css', '500.css', '700.css', '400-italic.css'], out: 'main' },
  { pkg: 'noto-sans-sc', files: ['400.css', '700.css'], out: 'zh' },
];
const keepSubsets = /(latin|latin-ext|cyrillic|cyrillic-ext|noto-sans-sc-\[\d+\])-/;

const header = '/* Generated by scripts/gen-fonts.mjs — do not edit by hand. */\n';
const css = {
  main: header + '/* Alegreya and Alegreya Sans by Juan Pablo del Peral (Huerta Tipográfica), SIL Open Font License 1.1. */\n',
  zh: header + '/* Noto Sans SC (Google, Adobe), SIL Open Font License 1.1. Loaded only for Simplified Chinese. */\n',
};
for (const { pkg, files, out } of wanted) {
  for (const file of files) {
    const source = readFileSync(resolve(root, 'node_modules/@fontsource', pkg, file), 'utf8');
    const blocks = source.split('/* ').slice(1);
    for (const block of blocks) {
      const name = block.slice(0, block.indexOf(' */'));
      if (!keepSubsets.test(name)) continue;
      const rule = block
        .slice(block.indexOf('@font-face'))
        .replace(/src: url\(\.\/files\/([^)]+\.woff2)\) format\('woff2'\), url\([^)]+\) format\('woff'\);/, (_m, f) =>
          `src: url(../../node_modules/@fontsource/${pkg}/files/${f}) format('woff2');`,
        )
        .trim();
      if (rule.includes("format('woff')")) throw new Error(`Unexpected source format in ${pkg}/${file}: ${name}`);
      css[out] += `\n/* ${name} */\n${rule}\n`;
    }
  }
}
for (const key of Object.keys(outputs)) {
  writeFileSync(outputs[key], css[key]);
  console.log(`Wrote ${outputs[key]} (${(css[key].length / 1024).toFixed(1)} KiB)`);
}
