"""Synthetic test fixture in the released AgentHorizon layout.

THIS IS TEST DATA, NOT BENCHMARK CONTENT. Every instruction, screenshot, and file is stamped
"SYNTHETIC FIXTURE", and a SYNTHETIC_FIXTURE.txt marker makes ingestion register the dataset version as
``fixture-synthetic`` (never ``agenthorizon``). It mirrors construction semantics so that pipelines, staging,
leakage audits and scoring can be exercised end to end without the real (currently unreachable) release:

* parent/child deliverable pairs, each with its own recording;
* positives (own instruction + own recording) and swapped negatives (other instruction + this recording);
* one excluded positive (review exclusion) and one untyped negative;
* a 320-step recording (longer than 300) and an unrecognised action variant.
"""

from __future__ import annotations

import json
import random
import uuid
from pathlib import Path

from PIL import Image, ImageDraw

from agenthorizon.data.markdown import render_markdown

MARKER_TEXT = ("SYNTHETIC TEST FIXTURE generated by agenthorizon.testing.fixture.\n"
               "Not AgentHorizon benchmark content. Never report scores on it as benchmark results.\n")

PAIRS = [
    # (parent instruction, child instruction, os, task_type, applications, n_steps, mistake types (inst2_demo1, inst1_demo2))
    ("SYNTHETIC FIXTURE: In the Files app, rename 'alpha.txt' to 'beta.txt' in Documents.",
     "SYNTHETIC FIXTURE: In the Files app, rename 'alpha.txt' to 'gamma.txt' in Documents.",
     "linux", "PRODUCTIVITY", ["Files"], 12, ("Misunderstanding of the Instructions", "Misunderstanding of the Instruction")),
    ("SYNTHETIC FIXTURE: Export the open slide deck as a high-resolution PNG.",
     "SYNTHETIC FIXTURE: Export the open slide deck as a high-resolution PNG and email it to the team list.",
     "windows", "CREATIVITY", ["Slides", "Mail"], 18, ("Bad Side Effect", "Critical Mistake")),
    ("SYNTHETIC FIXTURE: Book a meeting room for November 1 at 10:00.",
     "SYNTHETIC FIXTURE: Book a meeting room for November 11 at 10:00.",
     "macos", "GENERAL", ["Calendar", "Browser"], 320, ("Critical Mistake", None)),
    ("SYNTHETIC FIXTURE: Create a folder named 'Workspace' inside Documents.",
     "SYNTHETIC FIXTURE: Create a folder named 'Workspace' inside Desktop.",
     "windows", "DEVELOPMENT", ["Explorer", "IDE"], 9, ("Critical Mistake", "Misunderstanding of the Instruction")),
]
EXCLUDED_POSITIVE = (1, "child")  # pair index, side whose positive was excluded by evidence review


def _actions(rng: random.Random, n: int) -> list[dict]:
    kinds = ["click", "type", "press", "hotkey", "scroll", "drag", "move", "key_down", "key_up", "wait", "click"]
    out = []
    for i in range(n):
        k = kinds[i % len(kinds)] if i < n - 1 else "click"
        x, y = rng.randint(10, 1700), rng.randint(10, 1100)
        if k == "click":
            a = {"type": "click", "parameters": {"x": x, "y": y, "button": "left", "num_clicks": 1 + (i % 7 == 3)}}
        elif k == "type":
            text = "synthetic text " * (8 if i % 9 == 1 else 1)
            a = {"type": "type", "parameters": {"text": text.strip()}}
        elif k == "press":
            a = {"type": "press", "parameters": {"keys": ["Enter"]}}
        elif k == "hotkey":
            a = {"type": "hotkey", "parameters": {"keys": ["Ctrl", "s"]}}
        elif k == "scroll":
            a = {"type": "scroll", "parameters": {"x": x, "y": y, "direction": "down", "amount": 240}}
        elif k == "drag":
            a = {"type": "drag", "parameters": {"start_x": x, "start_y": y, "end_x": x + 40, "end_y": y + 10}}
        elif k == "move":
            a = {"type": "move", "parameters": {"x": x, "y": y}}
        elif k in ("key_down", "key_up"):
            a = {"type": k, "parameters": {"key": "Shift"}}
        else:
            a = {"type": "wait", "parameters": {"duration_s": 0.5}}
        out.append(a)
    if n > 5:
        out[5] = {"type": "synthetic_gesture", "parameters": {"note": "unrecognised action variant (fixture)"}}
    return out


def _png(path: Path, text: str, size: tuple[int, int], color: tuple[int, int, int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    im = Image.new("RGB", size, color)
    d = ImageDraw.Draw(im)
    d.rectangle([4, 4, size[0] - 5, size[1] - 5], outline=(255, 255, 255), width=2)
    d.text((12, 12), "SYNTHETIC FIXTURE", fill=(255, 255, 255))
    d.text((12, 30), text, fill=(255, 255, 0))
    im.save(path, format="PNG")


def build_fixture(out: Path, *, seed: int = 7, full_size_recordings: int = 1) -> dict:
    """Write the fixture to ``out``. Returns a summary including the private ground truth for tests."""
    rng = random.Random(seed)
    out = Path(out)
    sb = out / "sandbox" / "data"
    (out / "SYNTHETIC_FIXTURE.txt").parent.mkdir(parents=True, exist_ok=True)
    (out / "SYNTHETIC_FIXTURE.txt").write_text(MARKER_TEXT)
    deliverables = {}
    items = []
    for pi, (p_inst, c_inst, os_, ttype, apps, n_steps, (mt_21, mt_12)) in enumerate(PAIRS):
        for side, inst in (("parent", p_inst), ("child", c_inst)):
            did = f"{900000 + pi * 10 + (side == 'child'):09d}-fixture-{pi}{side[0]}"
            steps = []
            ts = 0
            size = (1710, 1112) if pi < full_size_recordings else (342, 222)
            color = (40 + pi * 40, 60, 90 + (side == "child") * 60)
            for si, act in enumerate(_actions(rng, n_steps)):
                img_rel = f"./data/media/images/{did}/step_{si + 1}.png"
                _png(sb / "media" / "images" / did / f"step_{si + 1}.png", f"pair {pi} {side} step {si}", size, color)
                steps.append({"step_id": si, "screenshot": img_rel, "action": act, "thought": None,
                              "action_description": None, "timestamp_us": ts})
                ts += rng.randint(150_000, 2_500_000)
            deliverables[(pi, side)] = {"did": did, "inst": inst, "steps": steps,
                                        "task": {"instruction": inst, "category": "Tool Usage", "subcategory": "GUI Agent",
                                                 "task_type": ttype, "applications": apps},
                                        "env": {"os": os_, "screen_resolution": None}}
        P, C = deliverables[(pi, "parent")], deliverables[(pi, "child")]
        for side, d in (("parent", P), ("child", C)):
            if (pi, side) == EXCLUDED_POSITIVE:
                continue
            items.append({"inst": d["inst"], "rec": d, "label": {"label": "positive", "original_id": d["did"]}})
        items.append({"inst": P["inst"], "rec": C, "label": {"label": "negative", "original_id": C["did"], "paired_id": P["did"],
                      "negative_source": "parent_instruction_child_trajectory", "mistake_type": mt_21}})
        items.append({"inst": C["inst"], "rec": P, "label": {"label": "negative", "original_id": P["did"], "paired_id": C["did"],
                      "negative_source": "child_instruction_parent_trajectory", "mistake_type": mt_12}})
    rng.shuffle(items)
    labels_main, labels_simple = [], []
    gold = {}
    for k, it in enumerate(items):
        tid = str(uuid.UUID(int=rng.getrandbits(128), version=4))
        rec = it["rec"]
        task = dict(rec["task"])
        task["instruction"] = it["inst"]
        traj = {"trajectory_id": tid, "task": task, "environment": rec["env"], "steps": rec["steps"]}
        (sb / "jsons").mkdir(parents=True, exist_ok=True)
        (sb / "markdowns").mkdir(parents=True, exist_ok=True)
        (sb / "jsons" / f"{tid}.json").write_text(json.dumps(traj, indent=2) + "\n")
        (sb / "markdowns" / f"{tid}.md").write_text(render_markdown(traj))
        lab = {"trajectory_id": tid, **it["label"]}
        if lab["label"] == "negative" and lab.get("mistake_type") is None:
            lab.pop("mistake_type")
        (labels_main if k % 2 == 0 else labels_simple).append(lab)
        gold[tid] = lab
    for name, rows in (("AgentHorizon.jsonl", labels_main), ("AgentHorizon-Simple.jsonl", labels_simple)):
        (out / name).write_text("".join(json.dumps(r) + "\n" for r in rows))
    (out / "README.md").write_text("# SYNTHETIC FIXTURE\n\n" + MARKER_TEXT)
    return {"root": str(out), "n_examples": len(items), "gold": gold,
            "n_positive": sum(1 for g in gold.values() if g["label"] == "positive"),
            "n_negative": sum(1 for g in gold.values() if g["label"] == "negative"),
            "label_files": {"AgentHorizon.jsonl": len(labels_main), "AgentHorizon-Simple.jsonl": len(labels_simple)}}
